### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode-livepreview#106]
The work on this has been great, have you considered running a changelog for users to keep track of?

Prior art is the js debug one https://github.com/microsoft/vscode-js-debug/blob/main/CHANGELOG.md

it offers visibility to changes (such as these https://github.com/microsoft/vscode-livepreview/pull/93) and makes it easy for users to scroll through/search change history.

I can understand if you don’t want to do this until you hit 1.0.0 though

**Comment by andreamah** [comment]
Great idea! Thanks so much for the suggestion, made a PR for it. 😊
