### ISSUE TITLE
[Feature request] Preview XML with XSL stylesheet

### ISSUE THREAD

**Issue by sntran** [microsoft/vscode-livepreview#118]
Some webservers (like Python's built-in one) can load an XML file with `<?xml-stylesheet type="text/xsl" href="../src/html.xsl"?>` and render it as the transformed HTML.

I would like to ask for support for this, even with a low priority. This would allow a small subset of developers that can preview their XML easily.

**Comment by bmix** [comment]
I don't know about the setup you are describing, but, commonly, it is not the web-server, that transform the XML into HTML, but it is the build-in XSLT (1.0 only) support in the web-browser. So, the `<?xml-stylesheet type="text/xsl" href="../src/html.xsl"?>` gets executed and rendered browser-side, not server-side. The browser gets the XML document and then requests the XSL document referenced in the processing-instruction. Then it utilizes its internal XSL processor (1.0 only, sadly) and renders the file.

**Comment by sntran** [comment]
Thanks for clarifying @bmix !

I guess it's then out of scope to add a simple xslt engine that can read the XSL file and transform it into the webview?

There is some libxslt binding for Node.js, but we probably don't want to include native module anyway. Closing this.

**Comment by bmix** [comment]
> I guess it's then out of scope to add a simple xslt engine that can read the XSL file and transform it into the webview?
 
> There is some libxslt binding for Node.js, but we probably don't want to include native module anyway. Closing this.

As far as I know, the browser's included XSLT engine *is* *libxslt*. *libxslt* is outdated technology, that is only capable of XSLT 1.0 (which is 20 years old, or so). Current XSLT version is 3.0 with XPath 3.1.

As I said, if you are fine with XSLT version 1.0 (which is the one *libxslt* implements), then you should be fine in rendering the XML in the browser. The result should be the same: An HTML page in the browser. I am not sure, however, whether the browser's development console shows the rendered XML (so, it would show the HTML DOM) or the XML DOM.

If you want more professional XML tools, then you'd need to set up something like a Jetty or Tomacat webserver, in which you run the Saxon XSLT processor in a pipeline. Or maybe Apache Cocoon.

**Comment by sntran** [comment]
> What is your use case?

My company still uses XML for data, and we use XSL to transform them into HTML page. For quick development, we cache the XML locally and edit them as we go. Therefore, being able to preview the rendered HTML with the XML would allow faster prototyping.

But it's definitely not a quick thing to add to this extension.
