### ISSUE TITLE
Audio and audio contained in a video file does not work with Internal Preview

### ISSUE THREAD

**Issue by Petarkco** [microsoft/vscode-livepreview#120]
Audio is unable to be played when using the HTML audio tag. It appears within the Internal Preview window as though a source has not been correctly provided (greyed out controls). The audio and file correctly loads and plays in an external browser (MS Edge being the browser here).

Additionally audio that is contained with a video file when using the HTML video tag also appears to not load. The video loads fine but audio is greyed out and does not play.

![image](https://user-images.githubusercontent.com/25685344/127111060-39e6e9c1-d496-4265-ad37-42c6014c960e.png)
![image](https://user-images.githubusercontent.com/25685344/127111092-e8dbf2e2-7044-4291-b620-32b16622516f.png)

**Comment by anburocky3** [comment]
Looks like vscode doesn't support audio tag.

https://github.com/microsoft/vscode/issues/66050#issuecomment-451548339

**Comment by RrTe** [comment]
Audio is also not loaded in Phaser when using Live Preview. The same Phaser code works with Live Server though.

**Comment by andreamah** [comment]
I believe that you should be able to preview the audio with the supported audio types. See here: https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_72.md#built-in-preview-for-some-audio-and-video-files. I tried an mp4 file with mp3 audio and it seemed to work fine.

Most mp4 files use AAC, but there are some legal concerns behind shipping support for that in the core editor, we can't support it. See https://github.com/microsoft/vscode/issues/167685 for more details.
