### ISSUE TITLE
Output console prints `undefined` for function objects

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-livepreview#128]
Testing microsoft/vscode#129445

Issue Type: <b>Bug</b>

1. Create an html file that logs a function-type object:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>fdsafasd</p>
    <script>
        console.log(() => {})
    </script>
</body>
</html>
```

**Bug**
In the output console, this prints `undefined`

However in the developer tools, this prints `() => {}` instead 

VS Code version: Code - Insiders 1.59.0-insider (c3b4df8f5d9c14aa4cfddb587231d0d52e72e5a2, 2021-07-27T15:07:54.419Z)
OS version: Linux x64 4.15.0-142-generic snap
Restricted Mode: No

**Comment by davixiao** [comment]
In media\injectScript.js:
```javascript
try {
  stringifiedMsg = JSON.stringify(msg);
} catch (err) {
  try {
    stringifiedMsg = msg.toString();
  } catch (err) {
    // noop
  }
}
```
JSON.stringify(()=>{}) produces undefined instead of an error, which could be the cause.
