### ISSUE TITLE
Url file name Chinese error

### ISSUE THREAD

**Issue by PromiseAll** [microsoft/vscode-livepreview#131]
No file was found after the URL was encoded

![image](https://user-images.githubusercontent.com/56338627/127462331-9142aa0e-f5b5-4827-96eb-167d9c0ceb0a.png)
![image](https://user-images.githubusercontent.com/56338627/127462366-2b4c7725-5fb2-4aa3-b274-a7d2ad739aa1.png)
#196

**Comment by yang-zyu** [comment]
I got the same problem when I tried to switch from "[Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer)" to "Live Preview". 

It seems that the url parser of "Live Preview" only recognize ascii codes, while UTF-8 is wanted.

**Comment by yang-zyu** [comment]
I got the same problem when I tried to switch from "[Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer)" to this "Live Preview". 

It seems that current URL parser of "Live Preview" only recognizes ASCII codes, while UTF-8 is wanted.

**Comment by lala7573** [comment]
url name korean also not working

**Comment by PromiseAll** [comment]
#196

**Comment by xrswyea** [comment]
Is there a solution?
