### ISSUE TITLE
Preview button missing

### ISSUE THREAD

**Issue by JoelFeiner** [microsoft/vscode-livepreview#136]
I've installed live preview and enabled it. I also started the server and I see that it is using port 3000 (I'm using remote-ssh). However, there is no button on the tab bar to preview HTML files, nor is there an option in the context menu.

![image](https://user-images.githubusercontent.com/20820071/128433449-5877551c-e3a9-4b84-918b-7918748de122.png)

Settings:
![image](https://user-images.githubusercontent.com/20820071/128433494-678866e0-759a-4b62-9c6d-2795c3ac8ead.png)

**Comment by andreamah** [comment]
Some questions:
1. Do you have an HTML file open? The preview button is only on HTML files.
2. Have you tried reloading your editor window?

**Comment by JoelFeiner** [comment]
@andreamah 

I opened a plain HTML file, from several different folders. No special extensions.

However, I decided to do some further inspection and Isee that my VSCode is incorrectly detecting these files as Django HTML. It seems to me that Django HTML should still count as HTML, though.

In any case, when I manually switch the type from Django HTML to HTML, the preview button appears.

If there is a bug to be fixed here it would be to allow for any file with .html in the filename to count, or for the user to be notified in some way that the file can't be previewed because of its detected type.

**Comment by Jassi10000** [comment]
You can right click anywhere on the screen , when in an HTML file , you will automatically see  a PREVIEW written there 
Click that and you are good to go

**Comment by andreamah** [comment]
@JoelFeiner do you still run into this?

**Comment by itsfaizalam** [comment]
Here is the correct answer just check the screenshot and you'll get your answer.

![image](https://github.com/user-attachments/assets/73ec081c-c3b8-4055-afcf-22f75014737a)

**Comment by marcelosperez** [comment]
You need to install an extension called "LIVE PREVIEW" for this option to show:


![Image](https://github.com/user-attachments/assets/a34df193-1756-4b95-887f-0218006a870f)
