### ISSUE TITLE
Multi-root settings missing, root is set to OS root.

### ISSUE THREAD

**Issue by anghelos** [microsoft/vscode-livepreview#143]
I can't find the setting appearing in #30.

In a multi-root workspace, It also does not open the first workspace folder as root (which is what I read was the behavior before multi-root support), but instead uses the full path to the OS root:
![image](https://user-images.githubusercontent.com/5363796/128731538-41dc728e-b512-4fee-b85c-9d63e915eb64.png)

(first workspace folder is _site/)
![image](https://user-images.githubusercontent.com/5363796/128731723-fefd9913-5371-4605-b7e6-3fbf8b746b3e.png)

Needless to say, relative links do not work either.

Is there something I'm missing?

**Comment by lszomoru** [comment]
@anghelos, apologies for not getting back to you on this until now. While pull request #30 contains the initial implementation of multi-root support, commit 442f12519f8104622ccfdfa7478afb136e42b4ed has refactors the multi-root support so that rather than picking the default workspace for the server, each workspace is being served on its own endpoint so that you can preview files from multiple workspaces. Could you please elaborate further on the issue with relative paths that you are experiencing? Thanks!

**Comment by anghelos** [comment]
I'm a little confused by your use of the word "workspace" here. Are you talking of multiple workspaces opened in separate windows, or multiple folders in the same workspace (which I believe is what multi-root support was supposed to cover)?

As for the relative path issue, This is the behavior I'm witnessing:

1. In a Workspace with a single root folder, relative paths work as expected.
2. After adding a folder to the workspace, the server's root is set to Windows' root.
3. If the added folder is a subfolder of the first, the server's root will remain tied to the first folder until the workspace is re-opened, then the same problem as 2 occurs.
4. If I remove the second folder, everything works as intended after I close and reopen the Studio Code window.

**Comment by lszomoru** [comment]
Agreed that the folder/workspace/multi-root workspace terminology is [confusing](https://code.visualstudio.com/docs/editor/workspaces). I have to say that I a little confused on step No3 that you have described above. What do you mean that the folder that you are adding is a subfolder of the first? In what scenario would you add a folder that is already present in the Explorer? Could you share the folder layout that you have an exactly which folders are you adding to the multi-root workspace? Thanks!

**Comment by lszomoru** [comment]
@anghelos, I have tried to reproduce your steps using the `test-workspace` folder from this repository. Here were my steps:
1. Open the `test-workspace` folder in VS Code. Open `subfolder_page.html` and preview it. Image using relative path works.
2. Add `test-workspace\subfolder` to the workspace. This is extremely weird as now you have this folder appear in "both" workspaces. Notice in the screenshot below that the image is still being loaded successfully. 

What am I missing? Thanks!

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/3372902/143478155-905de366-745d-4a2c-987a-029f4cf24881.png">

**Comment by anghelos** [comment]
Actually, you can see the bug right in your screenshot! The URL on the browser should be "http://127.0.0.1:3000/subfolder_page.html" (or even just "http://127.0.0.1:3000/")

To be honest, the only reason I'm adding this subfolder as a root folder is only because I want it to be the root for Visual Preview.
I'm using a static site generator (Eleventy, but this applies to all/most of them), which generates the web pages in a subfolder ("_site"). I want to preview those pages while still being able to use src="/folder/image.jpg" (instead of your "../").

**Comment by lszomoru** [comment]
Thanks @anghelos! Interestingly enough, that was implemented originally in this extension but then the functionality was removed and as you have stated, as soon as you have a multi-root workspace, all files are being served as an out-of-workspace file. I will try to get some context on why the functionality from #30 has been refactored and will circle back to this issue.

**Comment by ChrisAcrobat** [comment]
@lszomoru: Any news about this?

**Comment by falco467** [comment]
Hi! The current version seems even more broken. When I start live preview in a Workspace I get the following error message on the HTML preview:

File not found
The file "\c:\Workspace\myproject\function (old_index, new_index) { \ Shortcut helper to move item to end of array if (-1 === new_index) { new_index = this.length - 1; } if (new_index >= this.length) { var k = new_index - this.length; while (k-- + 1) { this.push(undefined); } } this.splice(new_index, 0, this.splice(old_index, 1)[0]); return this; \ for testing purposes }\index.html" cannot be found. It may have been moved, edited, or deleted.

It seems there is some Javascript code, which is not evaluated, but gets put directly into the URL.

**Comment by andreamah** [comment]
> version seems even more broken. When I start live preview in a Workspace I get the following error message on the HTML preview:
> 
> File not found The file "\c:\Workspace\myproject\function (old_index, new_index) { \ Shortcut helper to move item to end of array if (-1 === new_index) { new_index = this.length - 1; } if (new_index >= this.length) { var k = new_index - this.length; while (k-- + 1) { this.push(undefined); } } this.splice(new_index, 0, this.splice(old_index, 1)[0]); return this; \ for testing purposes }\index.html" cannot be found. It may have been moved, edited, or deleted.
> 
> It seems there is some Javascript code, which is not evaluated, but gets put directly into the URL.

@falco467 does this still happen?
