### ISSUE TITLE
The Content-Type of WebAssembly is not correct

### ISSUE THREAD

**Issue by shellyln** [microsoft/vscode-livepreview#144]
The following error will be displayed in the external browser console:
`Uncaught (in promise) TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
`

The response header will be returned with the following value:
`Content-Type: application/wasm; charset=UTF-8`

Another server returns `content-type: application/wasm`, and no error occurs.

**Bug**
The `charset=UTF-8` specified in content-type must not be added.

https://webassembly.github.io/spec/web-api/index.html#streaming-modules

> If the Response is not CORS-same-origin, does not represent an ok status, or does not match the `application/wasm` MIME type, the returned promise will be rejected with a TypeError; 

**Steps to reproduce**
1. Open a preview of the html that is loading WebAssembly.
    ```html
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8"/>
        <script src="wasm_exec.js"></script>
        <script>
            const go = new Go(); // Symbol in wasm_exec.js
            WebAssembly.instantiateStreaming(fetch("go.wasm"), go.importObject).then((result) => { // Error!
                ...
            });
        </script>
        <script>
    ...
    ```

Browser: Google Chrome 92.0.4515.131
VS Code version: 1.59.0
OS version: Windows 10 Pro 21H1
Restricted Mode: No

Extension version: 0.2.7

**Comment by jcyuan** [comment]
any update? this bug is still there...  i'm encountering the same

**Comment by KEINOS** [comment]
Same. This also applies to the integrated VSCode browser as well.

```javascript
___vscode_livepreview_injected_script:131 TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
(anonymous) @ ___vscode_livepreview_injected_script:131
```

I use `Remote - Container` extension and have added "`application/wasm wasm`" to the container's "`mime.types`" file, but without success.

- VS Code: 1.64.0
  - Electron: 13.5.2
  - Chromium: 91.0.4472.164
  - Node.js: 14.16.0
  - V8: 9.1.269.39-electron.0
  - OS: Darwin x64 19.6.0
- Live Preview: 0.2.12

**Comment by jcyuan** [comment]
> Same. This also applies to the integrated VSCode browser as well.
> 
> ```js
> ___vscode_livepreview_injected_script:131 TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
> (anonymous) @ ___vscode_livepreview_injected_script:131
> ```
> 
> I use `Remote - Container` extension and have added "`application/wasm wasm`" to the container's "`mime.types`" file, but without success.
> 
> * VS Code: 1.64.0
>   
>   * Electron: 13.5.2
>   * Chromium: 91.0.4472.164
>   * Node.js: 14.16.0
>   * V8: 9.1.269.39-electron.0
>   * OS: Darwin x64 19.6.0
> * Live Preview: 0.2.12
> 
> My current workaround is to use the [Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) extension instead, but I would prefer to use the official extension.

i'm using IIS Express, because i develop with asp.net too so very familar with it, IIS Exporess + web.config can almost done everything you need, but the drawback is it does not support instant refresh.
anyway i use LivePreview as well, so still hope that this issue can be fixed by official.

**Comment by shellyln** [comment]
Whether "; charset=UTF-8" is added or not should be checked if the contentType starts with "text/".

https://github.com/microsoft/vscode-livepreview/blob/145f83606455f0b53f175f05142aa3a2d6632ea2/src/server/httpServer.ts#L144-L154

https://github.com/microsoft/vscode-livepreview/blob/145f83606455f0b53f175f05142aa3a2d6632ea2/src/server/httpServer.ts#L181-L190

https://github.com/microsoft/vscode-livepreview/blob/145f83606455f0b53f175f05142aa3a2d6632ea2/src/server/httpServer.ts#L245-L255

**Comment by cuixiping** [comment]
Thank @shellyln 

https://github.com/microsoft/vscode-livepreview/blob/145f83606455f0b53f175f05142aa3a2d6632ea2/src/server/httpServer.ts#L245-L255

I modified the 3rd place code line 252 to 
```
 	'Content-Type': contentType=='application/wasm' ? contentType :  `${contentType}; charset=UTF-8`, 
```

It works.

I know this is a ugly modification. 
Expect a PR to fix this issue.

**Comment by roblourens** [comment]
Got a test app I can use?

**Comment by andreamah** [comment]
You can use this: [testwasm.zip](https://github.com/microsoft/vscode-livepreview/files/9427233/testwasm.zip)
