### ISSUE TITLE
Configurable basePath

### ISSUE THREAD

**Issue by chen-ye** [microsoft/vscode-livepreview#145]
Hey there--I'm using this extension in a monorepo context, where the website I'd like to preview is rooted inside a subdirectory:

Would it be possible to have a configurable basePath, so that 

`project/frontend-a/foo.html` (where vscode is opened to `project`)

Is hosted as 

`http://localhost:8080/foo.html`

?

**Comment by andreamah** [comment]
Hi! You can actually edit the port that the server is hosted on using the setting for `livePreview.portNumber`. By default, it's on port 3000, but you can change that to 8000

**Comment by chen-ye** [comment]
Hey @andreamah !

Unfortunately, that isn't quite what I meant--the feature that I'd find useful is the ability for the http server to host
`{workspaceFolder}/frontend/index.html` (for example)
at
`http://localhost/index.html`,
rather than the current non-configurable
`http://localhost/frontend/index.html`.

Likewise, absolute URIs, such as `import '/lib/module.js` could resolve to `{workspaceFolder}/frontend/lib/module.js`, rather than `{workspaceFolder}/lib/module.js.

**Comment by chen-ye** [comment]
@andreamah Do you mind reopening this issue? Like I mentioned, I don't think this is addressed by the extension's current featureset.

**Comment by andreamah** [comment]
Hi! Sorry for not getting back to you earlier about this. Looking into it again, this looks a little like https://github.com/microsoft/vscode-livepreview/issues/155. Let me know if that's what you were thinking about.
