### ISSUE TITLE
[Feature request] Support SHTML with Server Side Includes

### ISSUE THREAD

**Issue by sntran** [microsoft/vscode-livepreview#147]
Many webservers like IIS, Apache, nginx support SSI, mostly the `#include` directive. I think vscode already has all the functionality to parse, fetch and replace the SSI when rendering the `.shtml` file for live preview.

Please consider adding support for SSI.

**Comment by andreamah** [comment]
It might be a little tricky to incorporate SSI into a node server. There doesn't seem to be a really popular way to incorporate SSI into node, and incorporating it manually might make the server more heavy than desired. Closing this for now, but am open to feedback on this.
