### ISSUE TITLE
New feature request: please add font scale for better view

### ISSUE THREAD

**Issue by touchft** [microsoft/vscode-livepreview#150]
thx

**Comment by Jassi10000** [comment]
@misolori Sir , I want to give this issue a shot , can you pls assign me

**Comment by andreamah** [comment]
Is this the font scale of the address bar? or scale of the actual content? Content zoom is covered here: #113

**Comment by touchft** [comment]
This is for scale of the actual content.

**Comment by andreamah** [comment]
duplicate of  #113
