### ISSUE TITLE
latest changes often do not appear

### ISSUE THREAD

**Issue by Lomacar** [microsoft/vscode-livepreview#151]
Very often I find that the latest changes made to a document are not entirely reflected in the  preview. For example, I will type a word in an HTML document, and the last two letters of the word are missing. I get the feeling that the preview is refreshing too eagerly but a bit randomly. 

I think the live preview should wait a little longer for input to stop before refreshing? Maybe this should be a tweakable setting? I think I will switch to updating on save for now.

**Comment by Jassi10000** [comment]
I guess it needs an update , check that once 
Or try uninstalling and then installing

**Comment by andreamah** [comment]
I can't seem to replicate that particular issue, but I'll add a feature request to include debounce

**Comment by andreamah** [comment]
implementing debounce would be a duplicate of #174
