### ISSUE TITLE
Bug: Show Debug Preview always opens Chrome

### ISSUE THREAD

**Issue by Pawper** [microsoft/vscode-livepreview#152]
Hello 👋 The readme instructs that, with the Edge Devtools Extension installed, I should be able to go to the Command Palette and enter **Live Preview: Show Debug Preview (External Browser)** and it should launch Edge along with the Edge Devtools Extension (Edge is set as my system's default browser). I even set up a launch.json configuration through the Edge Devtools Extension.

**Live Preview: Show Debug Preview (External Browser)** always launches Chrome, though.

Also, this is the launch.json configuration it offers.
```
    "configurations": [
        {
            "type": "pwa-chrome",
            "name": "http://127.0.0.1:3000/index.html",
            "request": "launch",
            "url": "http://127.0.0.1:3000/index.html"
        }
    ]
```
But this configuration doesn't start Live Preview when launched separately, and also gives this message in the debug console: `crbug/1173575, non-JS module files deprecated.`

**Live Preview: Show Preview (External Browser)** does not share this behavior. It launches my system's default browser (Edge).

I would like to start the live preview server and Edge Devtools Extension with a single action.

**Comment by andreamah** [comment]
That's pretty strange, I get something like:

```
        {
            "type": "msedge",
            "name": "http://127.0.0.1:3000/index.html",
            "request": "launch",
            "url": "http://127.0.0.1:3000/index.html"
        }
```

If you're still getting this, do you have any non-default settings for the Javascript debugger?
