### ISSUE TITLE
Ctrl+Shift+F triggers search

### ISSUE THREAD

**Issue by brunnerh** [microsoft/vscode-livepreview#153]
I expected search to only trigger for Ctrl+F.

The page I was previewing has its own search implementation using the shortcut Ctrl+Shift+F which gets overridden by the current behavior.

**Comment by Abheetarora** [comment]
hi @brunnerh actually ctrl+shift+F is already defined in vs code for "search in files" 
Ctrl+F will still work for the current file you are at.
Ctrl+shift+F will search between all the files present
I hope this would resolve your issue.

**Comment by brunnerh** [comment]
The preview runs in an `iframe`, so keyboard shortcuts of VS code are not triggered anyway.
The problem is that the preview accepts more than just Ctrl+F,

Here is the code from [`media/main.js`](https://github.com/microsoft/vscode-livepreview/blob/main/media/main.js):

```js
// listen for CTRL+F for opening the find menu
document.addEventListener('keydown', (e) => {
	ctrlDown = e.ctrlKey || e.metaKey;
	if ((e.key == 'F' || e.key == 'f') && ctrlDown) {
		showFind();
	}
});
```

Because this does not check for the state of `e.shiftKey`, it triggers in both cases.
