### ISSUE TITLE
[Feature request] Add a setting for the root of server

### ISSUE THREAD

**Issue by Heromyth** [microsoft/vscode-livepreview#155]
It seems necessary that a new setting for the root of server like what the LiveServer does. 

See `liveServer.settings.root` in https://github.com/ritwickdey/vscode-live-server/blob/master/docs/settings.md.

Thanks.

**Comment by SuyashSonawane** [comment]
Hi @lszomoru is this issue available for contribution ?

**Comment by tonny008** [comment]
add another setting for the context path.
so that we can serve `liveServer.settings.root` to the context path.
for example: 
serve `./dist/` to `localhost:3000/cool/feature/`
