### ISSUE TITLE
Find widget icon background

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode-livepreview#156]
On some themes the background of the icon does not match the background of the input field:
<img width="329" alt="image" src="https://user-images.githubusercontent.com/3372902/132347494-d62eaca4-e70b-46c0-9f66-3d5410c32bb7.png">

**Comment by lramos15** [comment]
@lszomoru how do you expect verification of these? I think I need to wait for a new version of live preview to be published or should I just build the sources

**Comment by lszomoru** [comment]
@lramos15, I will try to publish a new version of the extension today.

**Comment by lszomoru** [comment]
Extension has been updated in the marketplace.
