### ISSUE TITLE
Find widget - navigating between hits causes icon flicker

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode-livepreview#157]
Repro steps:
1. Open an `.html` file, and open the preview of the file
2. Open the `Find in Page` widget and look for a string that exists on the page
3. Hit the `Forward` and `Backward` navigation buttons

Expected: Find widget icon should not flicker
Actual: Find widget icon flickers

**Comment by connor4312** [comment]
@lszomoru it looks like 0.2.9 with this fix didn't get published

**Comment by connor4312** [comment]
ping @lszomoru

**Comment by lszomoru** [comment]
I have fixed the issue with the publishing pipeline and updated the extension.
