### ISSUE TITLE
Could this extension be core and extensible part of VS Code?

### ISSUE THREAD

**Issue by michaljerabek** [microsoft/vscode-livepreview#165]
Hi, it would be great to make this extension core part of VS Code that could be extended by users. We could develop extensions providing some features from Brackets (which is no longer supported by Adobe) like selector highligting, live CSS updating, clicking on element in the browser moves cursor to the position in the source, etc... Or you can add these features into this extension :) (The point is to be able to make all these features with only one connection working together and without the need to create separete extensions for browsers.)

Thanks for considering.

**Comment by michaljerabek** [comment]
(I was expecting at least some answer...)

**Comment by lszomoru** [comment]
Sorry. At the moment there are no plans to make this extension part of VS Code core, or make it extensible.
I did extract your request to add some feature from Brackets into this extension - https://github.com/microsoft/vscode-livepreview/issues/169.
