### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by adityaspaudel** [microsoft/vscode-livepreview#177]
- Issue Type: `Bug`
- Extension Name: `live-server`
- Extension Version: `0.2.9`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.62.3`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by adityaspaudel** [comment]
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 77,
		"activateCallTime": 29,
		"activateResolvedTime": 195,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-vscode.live-server",
				"_lower": "ms-vscode.live-server"
			},
			"activationEvent": "onLanguage:html"
		}
	},
	"runtimeErrors": [],
	"runningLocation": 1
}
```

**Comment by lszomoru** [comment]
@adityaspaudel, could you please describe the issue that you are experiencing? Thank you!
