### ISSUE TITLE
Whether the auto-generated task terminal has logging BUG

### ISSUE THREAD

**Issue by Angelo-yu** [microsoft/vscode-livepreview#178]
VS code version 1.62.3
OS version macOS Monterey 12.0.1(M1 chip)
Nodejs version: v14.18.1

Displaying logs has been enabled, but the console still does not display logs。
![image](https://user-images.githubusercontent.com/52949307/143200721-a7103c3a-5961-47f7-8b61-2f9a980514dd.png)

**Comment by andreamah** [comment]
I think you might be confusing the task terminal and the embedded live preview console. To see things like `console.log()`, Go to `Output` > `Embedded Live Preview Console` to see these. See https://github.com/microsoft/vscode-livepreview#console-output-channel-for-embedded-preview
