### ISSUE TITLE
Missing Devtools in Live Preview

### ISSUE THREAD

**Issue by necm1** [microsoft/vscode-livepreview#181]
Hello!

I'm not sure, but triggering `Simple Browser` doesn't have the option to trigger the `devtools`. I guess it doesn't exists for `Simple Browser` and would be glad if you could add it.

**Comment by Supportic** [comment]
Click on the hamburger icon and select "Open Devtools Pane".
Also, what stops you from opening a browser, resize the editor and the browser 50%/50% and use it this way with proper tools?
I guess this issue can be closed.

**Comment by andreamah** [comment]
Hi! Are you asking to add devtools to Simple Browser? Because if so, you'll need to file that in the vs code core repo instead.
