### ISSUE TITLE
Extension is not working

### ISSUE THREAD

**Issue by eliassal** [microsoft/vscode-livepreview#182]
hi, I installed this extension opened a workspace where I have  only html pages, I right click, chose Live Preview or click on the button in the right up corner but nothing happens.
thanks for your help

MyVS code versionand details

> Version: 1.62.3 (user setup)
> Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
> Date: 2021-11-17T08:11:14.551Z
> Electron: 13.5.2
> Chrome: 91.0.4472.164
> Node.js: 14.16.0
> V8: 9.1.269.39-electron.0
> OS: Windows_NT x64 10.0.19042
>

**Comment by huipingchen** [comment]
The same problem happened after the update of 1.62.3, it worked just two days ago.  but I made a fresh install on the other PC it works.

**Comment by huipingchen** [comment]
Version: 1.63.2 (system setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by huipingchen** [comment]
I try uninstalling vscode completely and delete the %userprofile%\.vscode and %appdata%\Code folder and reinstall it again. sign in with Microsoft account and it works.

**Comment by Supportic** [comment]
Try going into vscode extension settings and chose to open in external browser.
Right click on the HTML file and try starting the server again.
If a tab opens saying "Opening server..." and still nothing happens try to open the terminal as administrator:
```
net stop winnat
-- start the server --
net start winnat
```

**Comment by Neoniq** [comment]
I Confirm - restart eliminates the problem, but it persist again after pc reboot.

**Comment by andreamah** [comment]
Are you all still running into this issue with the newest version of VS Code?

**Comment by eliassal** [comment]
For me no it is working fine now
