### ISSUE TITLE
Support using local server instead of creating one

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-livepreview#187]
<img width="912" alt="CleanShot 2021-12-08 at 10 55 55@2x" src="https://user-images.githubusercontent.com/35271042/145267382-d7c75b13-89c7-45b3-83ce-cca0a317608c.png">

When used with other front-end frameworks that already provide a local server (React, Next, Hugo, etc.) it would be great if live preview could have an option to just preview the site at a given URL instead of generating one. This is a more "true" preview of the site.

**Comment by kentr** [comment]
FWIW, this can be achieved with the [`Simple Browser: Show` command](https://github.com/microsoft/vscode-livepreview/blob/20353ee012c60b75d41dd2e642f2fa7bc151c992/README.md?plain=1#L7).

**Comment by misolori** [comment]
This is handled by simple browser so there is no need for it

**Comment by johnfn** [comment]
Not sure if I'm misunderstanding, but Simple Browser lacks a large amount of the functionality that live preview has, making it virtually unusable for anything other than toy development. Most notably, it doesn't have a debugger or any way to view console.log() output. I'd recommend reopening this issue.
