### ISSUE TITLE
Live Preview Always show my old workspace but shows correctly in browser

### ISSUE THREAD

**Issue by arnav-kr** [microsoft/vscode-livepreview#191]
Actually previously I worked on a workspace and used live preview in that and when I closed the workspace and open a different workspace and then use live preview in that it always shows the old workspace's content in vs code
here's the screenshot of the old workspace that shows in the vs code
<img width="392" alt="image" src="https://user-images.githubusercontent.com/72879799/147366328-fe1ee196-36d6-4cc7-8a93-4dcb72ec0982.png">

But in the browser it is showing the correct workspace 
<img width="559" alt="image" src="https://user-images.githubusercontent.com/72879799/147366392-a2ef51c0-e4dc-498b-9dab-90e26100eb99.png">

Is there a fix for this bug
I tried reopening it but still the same 
i was working fine for some days but today it still started showing old one

**Comment by arnav-kr** [comment]
Oh, Actually It was Caused Due to Old Registered Service Worker That stayed there even when I closed the old workspace.
And Also no service workers were shown in the dev tools `service workers` tab so I didn't notice it earlier
<img width="413" alt="image" src="https://user-images.githubusercontent.com/72879799/147366768-2fae0d28-aa32-4b49-86ca-c33533169848.png">
So I have to manually Unregister it using javascript

If anyone else is facing the same problem then just unregister the workers from the dev tools javascript console by running the following code
```js
navigator.serviceWorker.getRegistrations().then(function(registrations) {
 for(let registration of registrations) {
  registration.unregister()
 } 
});
```

and make sure that your scope is the iframe
<img width="475" alt="image" src="https://user-images.githubusercontent.com/72879799/147366857-76410f26-ada6-4efa-9250-30090cd41403.png">

> And, The Devs of The Live Preview Please look for the possible fix for the bug

**Comment by ff6347** [comment]
I'm having the same problem. Unfortunately running the unregister does not work for me. I'm getting the following error:

```
Promise {<rejected>: DOMException: Failed to get ServiceWorkerRegistration objects: The document is in an invalid state.}
log.ts:439   ERR Failed to get ServiceWorkerRegistration objects: The document is in an invalid state.
___vscode_livepreview_injected_script:141 ServiceWorker registration successful
navigator.serviceWorker.getRegistrations().then(function(registrations) {
 for(let registration of registrations) {
  registration.unregister()
 } 
});
```
