### ISSUE TITLE
Calling livePreview.start from tasks.json does not work

### ISSUE THREAD

**Issue by blooop** [microsoft/vscode-livepreview#199]
I am trying to call the command to start the server as defined here:
https://github.com/microsoft/vscode-livepreview/blob/main/package.json#L53

based on the docs on calling commands in extensions from tasks.json:
https://code.visualstudio.com/docs/editor/variables-reference#_command-variables

My tasks.json looks like:

            {
			"label": "view docs", 
			"command": "${command:extension.livePreview.start}", 
		},
		{
			"label": "test calling command from task", 
			"command": "${command:editor.action.addCommentLine}", 
		},

I've confirmed I can call commands with the second task. but when trying to call the live preview command it says 
"command "extension.livePreview.start not found.

Any idea why it is not getting detected?

Thanks

**Comment by blooop** [comment]
And I am able to run F1 > "Live Preview : Start Server"  so the extension is working properly otherwise.

**Comment by richard-scott** [comment]
Look for the Command ID in the Keyboard Shortuct's section and it will show you the right one to use:

```
        {
		"label": "view docs", 
		"command": "${command:livePreview.start}", 
	},
```

**Comment by blooop** [comment]
Thanks! I could have sworn I tried that and other variations before making the issue, but clearly not!
