### ISSUE TITLE
Preview shows up, but code Typing is impossible

### ISSUE THREAD

**Issue by jan-kiessling** [microsoft/vscode-livepreview#200]
Hi, i am new at coding and MS Studio.
 can't get a preview to run. The MS Preview works, but after activating I can't type any code. Only 2-3 characters and suddenly the keyboard focus i gone. Cursor is gone as well. If i click back in it reappears and so forth...
I googled a lot, but could not solve it. I am working on an Intel Mac.

**Comment by arnodirlam** [comment]
Same here. The preview tab steals the focus very frequently, making it impossible to keep working in any other tab.

**Comment by arnodirlam** [comment]
Seems to be a duplicate of #160.

**Comment by andreamah** [comment]
> Seems to be a duplicate of #160.

Yup! This issue will be tracked there.
