### ISSUE TITLE
Auto Refresh Preview On All Changes in Editor won't auto refresh.

### ISSUE THREAD

**Issue by gajang** [microsoft/vscode-livepreview#202]
Since yesterday no form of preview will auto refresh, even after fresh installs and trying older versions.
I'm at a loss as to why, I can't think of any more solutions and this small problem is a bigger hit to my workflow than expected

**Comment by andreamah** [comment]
Are you still running into this issue? Can you double-check the `livePreview.autoRefreshPreview` setting to make sure that it's not set to `Never`?
