### ISSUE TITLE
Why no CSS?

### ISSUE THREAD

**Issue by 101is5** [microsoft/vscode-livepreview#203]
Is there a way to make it preview the whole project, not just the html files?

**Comment by JensMertelmeyer** [comment]
It works perfectly fine with css files. Can you outline the steps needed to reproduce your problem?

**Comment by 101is5** [comment]
It's a simple standard html/css/js project. Html files are linked to their css files normally. As of yet, only html shows, as if their <link> tags weren't there. Could it be the usage of Bootstrap? I am using two css sources: Bootstrap and a second css file.

**Comment by andreamah** [comment]
@101is5 I can't reproduce the issue. Can you let me know what code you use to trigger the issue?
