### ISSUE TITLE
Zoom level

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [microsoft/vscode-livepreview#206]
Issue Type: <b>Bug</b>

The Zoom level of embedded preview should not be the same as the main windows but the real size as in external browser.

Extension version: 0.2.12
VS Code version: Code - Insiders 1.66.0-insider (f407da25ec62fc82d8f038eb4ae0df1fe8ff246a, 2022-03-10T05:17:18.835Z)
OS version: Linux x64 5.13.0-35-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.29GB (8.38GB free)|
|Process Argv|--unity-launch --crash-reporter-id 4969aada-1424-402e-a01e-e34f76270a6a|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
pythonvspyl392:30422396
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
vsclayoutctrc:30405799
dsvsc009:30440021
pythonvsnew555:30438690
vsbas813:30436447
vscscmwlcmt:30428973
vscgsvidc:30433759
dockersurvey3cf:30438169
vscaac:30438845
pynewfile477cf:30443520

```

</details>

**Comment by JensMertelmeyer** [comment]
See #184 and #113 for duplicates

**Comment by ncodefun** [comment]
I still have this problem; Didn't understand why the preview was too big... It follows the UI zoom!??
