### ISSUE TITLE
Add web container support to run deno natively in browser only

### ISSUE THREAD

**Issue by beingminimal** [microsoft/vscode-livepreview#216]
Stackblitz has achieved this 1 year ago for nodejs. [see here](https://blog.stackblitz.com/posts/introducing-webcontainers/).
Also they have open sourced that project [here](https://github.com/stackblitz/webcontainer-core).

This extension should also support [deno](https://deno.land/) natively in any V8 engine based browser.
Such tech & tools will open a whole new era of web development for both frontend code and backend code.

@andreamah @lszomoru @mjbvz @usernamehw @davixiao @lramos15
Please consider this as DX improvement and give some priority to it.

Let me know if any type of further efforts are required from my side.
Thanks

**Comment by andreamah** [comment]
Not planned, see response for #215.
