### ISSUE TITLE
Is it able to Highlight the text you're working on?

### ISSUE THREAD

**Issue by doland** [microsoft/vscode-livepreview#217]
...like Five Server does and scroll when you scroll the code window? If so how?

**Comment by andreamah** [comment]
I believe that this would be a part of #149

**Comment by candideu** [comment]
If you're still looking for an alternative VS Code extension: [Five Server](https://github.com/yandeu/five-server-vscode) is able to jump to a section of a preview when you double-click or edit a section of your code. It can also highlight the code you are working on in your browser, update your files instantly while typing on your keyboard, and navigate your live preview automatically to the current editing file.

![image](https://raw.githubusercontent.com/yandeu/five-server/main/img/vscode-preview.gif)

Only downside is that there's no Workspace Multi-root support yet.
