### ISSUE TITLE
Allow Using Embedded Preview Without Launching Server

### ISSUE THREAD

**Issue by peacememories** [microsoft/vscode-livepreview#219]
Hi everyone, and thanks for this neat extension. I've found it very useful especially when teaching people the basics of web development, where I can give them a pretty modern experience without them having to learn about live servers and build tools etc.

I would like to use this extension for myself as well though. Especially the part of the extension that allows me to run a small browser within VSCode. This would make it much easier to stream myself working in tools like discord without sharing my whole screen. I think this is possible by starting the server and then just navigating to a different url, but that means an open port in the background and a few extra steps when starting up.

Thanks for considering this :wave:

**Comment by andreamah** [comment]
I think that what you're looking for is `Simple Browser`, which comes with VS Code. Try running `Simple Browser: Show` in the command palette (`CTRL`+`SHIFT`+`P`). 🙂
![image](https://user-images.githubusercontent.com/31675041/180896340-bf20ff38-dbf4-471d-8f73-2f5754b604e3.png)

**Comment by mrexodia** [comment]
I think what's missing from the Simple Browser is the 'Embedded Live Preview' output with the console logs (and the dev tools in general). I'm learning some web development now and it baffles me that you cannot disable the server functionality of the Live Preview extension and make it navigate to an address of your choosing.

As an example [codepen.io](https://codepen.io/mrexodia/pen/poLZYag) has an embedded console which makes it really easy to experiment with things and everything is nicely in a single application too.
