### ISSUE TITLE
[Bug]Doesn't work when path contains Chinese characters

### ISSUE THREAD

**Issue by henofdante** [microsoft/vscode-livepreview#224]
> File not found
> The file "d:\Code\WebFrontEnd\CSSLearning\03Ã¥Â…ÂƒÃ§Â´Â Ã¦Â˜Â¾Ã§Â¤ÂºÃ¦Â¨Â¡Ã¥Â¼Â.html" cannot be found. It may have been moved, edited, or deleted.

**Comment by Cinux-Chosan** [comment]
Same error!

**Comment by andreamah** [comment]
Duplicate of #131
