### ISSUE TITLE
BUG: Dosent open In Browser

### ISSUE THREAD

**Issue by iDevYT** [microsoft/vscode-livepreview#225]
_it just opens explorer_

**Comment by digitarald** [comment]
I hit the same issue. The _Open in Browser_ button seems to come from the _volar_ vue extension. LivePreview's menu has the real option.

Can you verify, @iDevYT ?

**Comment by iDevYT** [comment]
yes

**Comment by andreamah** [comment]
Closed with https://github.com/johnsoncodehk/volar/issues/1611, I believe.
