### ISSUE TITLE
Live Preview was working but now the icon / right click option are not visible

### ISSUE THREAD

**Issue by gclcodeguy** [microsoft/vscode-livepreview#230]
Live Preview was working fine earlier this week.

Now i cannot see the Live Preview icon, or see the option if i right click on the html.index file.

I have tried deleting the extension and re-downloading, enabling / disabling all extensions, nothing in the status bar, restarting laptop etc.

Any other tips to get icon back?

**Comment by andreamah** [comment]
Are you still running into this issue? Are these what you aren't seeing? 
![image](https://user-images.githubusercontent.com/31675041/180894394-d791d96c-d163-4ad7-af86-5fa0e48bbdb0.png)

I can't seem to reproduce your issue.

**Comment by gclcodeguy** [comment]
No don’t worry - solved. For some reason just one file was not allowing the preview, I think because it didn’t think it was html. It worked with a new file and not had any issue since!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
