### ISSUE TITLE
unresponsive

### ISSUE THREAD

**Issue by faseesinayomide** [microsoft/vscode-livepreview#231]
- Issue Type: `Bug`
- Extension Name: `live-server`
- Extension Version: `0.2.12`
- OS Version: `Windows_NT x64 10.0.18363`
- VS Code version: `1.68.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by digitarald** [comment]
If this happens please make sure to paste the diagnostic details from the clipboard.
