### ISSUE TITLE
Embedded Live Preview Console not in DropDown menu?

### ISSUE THREAD

**Issue by RoyKM** [microsoft/vscode-livepreview#237]
Hi, I'm using Visual Studio Code 1.66.2 and Live Preview released 6/21/2021 on 16:33:59 last updated 1/11/2022 09:04:30. When I open Live Preview it doesn't show the Console in the drop down menu, which only contains "Open in Browser", "Find in Page", and "Open DevTools Pane".  It does not have "Embedded Live Preview" like the Live Preview extension Details says about the "Console Output Channel (For Embedded Preview)", which says: "go to the Output tab and select Embedded Live Preview Console in the dropdown".  I found I can open devtools pane and see the console, but I was hoping I could see the console just under the Live Preview split screen
![LivePreviewScreenPrint](https://user-images.githubusercontent.com/79272297/179239067-b3929d7a-ec7b-46c5-b7ef-3a782bc2df32.png)
.

**Comment by andreamah** [comment]
You'll need to open the output console using `CTRL`+`SHIFT`+ ``    ` `` and then navigate to `OUTPUT`. See the gif below:
![Recording 2022-07-25 at 16 30 24](https://user-images.githubusercontent.com/31675041/180892112-c5f581e6-e62d-48d1-a574-22028598a93e.gif)
