### ISSUE TITLE
Setting for refresh on save is too vague

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode-livepreview#242]
> ...
> I also would like to mention that the name "On Changes to Saved Files" is not very clear to me. How about "On saving changes" or something similarly simple?

originally by @konsth191 at https://github.com/microsoft/vscode-livepreview/issues/235

**Comment by andreamah** [comment]
Reviewing this, I believe that something like "On Saving Changes" would be sort of unclear also, since some file watchers just overwrite existing files. Would that count as "Saving Changes?". I still think that "On Changes to Saved Files" is clearer, but let me know if you have extra input on this.

**Comment by oliviercailloux** [comment]
I concur. It is unclear what the “to Saved Files” part is supposed to mean in “On Changes to Saved Files”. Was the intent to distinguish this from “On Changes to Unsaved Files”?

If it means “On save”, then please name it as such.

**Comment by andreamah** [comment]
It's "On Changes to Unsaved Files" because changes might not necessarily be from the user explicitly saving from the editor (eg: filewatchers changing the file can trigger it).

**Comment by oliviercailloux** [comment]
Thank you for this clarification. On my version of VSCode I see “On Changes to Saved Files”. Either way, it is unclear and does not mean “On changes by a human being”.
