### ISSUE TITLE
[Question] Unable to install because it is not compatible

### ISSUE THREAD

**Issue by Rullec** [microsoft/vscode-livepreview#247]
Thanks for all of your work on this excellent plugin!

But when I try to install it from the marketplace, it complains as `Unable to install 'ms-vscode.live-server' extension because it is not compatible with the current version of VS Code (version 1.54.1).`

How to handle it? Thanks!
***
And my vscode version is 

Version: 1.54.1 (Universal)
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:42:18.719Z (1 yr ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

**Comment by andreamah** [comment]
You'll need to update your vscode version, as your version seems to be from February from last year. The newest version should be 1.70.
