### ISSUE TITLE
Not able to launch Live Preview within a Linux container

### ISSUE THREAD

**Issue by Selva-Aravinth-K** [microsoft/vscode-livepreview#249]
While using live preview with vs code in a Linux container, it was not able to connect to the localhost server(**http://localhost:3000**). It was not working with the Simple browser as well.
Please let me know whether it was a **Bug/Feature request** or am i missing any **configuration of Live preview** with respect to the **containerization**. PFB for the reference. 
![image](https://user-images.githubusercontent.com/110442834/182293628-dc4233f3-f1fb-4ea1-97b2-bb0810908640.png)
And also getting Websocket connection failed error. PFB,
![image](https://user-images.githubusercontent.com/110442834/182298968-ed0bfe7c-18ae-4607-9c8d-87aa779a56e0.png)

**Comment by andreamah** [comment]
When you're using a Linux container, are you also forwarding the port? See here: https://code.visualstudio.com/docs/remote/containers#_forwarding-or-publishing-a-port
