### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by GinoongFlores** [microsoft/vscode-livepreview#253]
- Issue Type: `Performance`
- Extension Name: `live-server`
- Extension Version: `0.2.13`
- OS Version: `Linux x64 5.4.0-122-generic`
- VS Code version: `1.70.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///tmp/ms-vscode.live-server-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

How can I attach a CPU-Profile on Linux?

**Comment by andreamah** [comment]
Hi, are you still running into this?

**Comment by GinoongFlores** [comment]
Hello @andreamah, I haven't encountered or noticed that issue again for quite some time. But do you have any tips or references to counter that issue if it could occur again? 

Thanks!

**Comment by andreamah** [comment]
You could take a look at https://github.com/microsoft/vscode/wiki/Performance-Issues to see what processes are taking up high load. I also would be interested in what exactly you're doing with the extension when it causes high load.

**Comment by GinoongFlores** [comment]
I'll update if I already take a look at it. Thanks for the insights.
