### ISSUE TITLE
How to run server automatically during debugging without preview

### ISSUE THREAD

**Issue by aetos382** [microsoft/vscode-livepreview#258]
I would like to debug simple HTML + JS code easily.
When I press the F5 key, I want the web server to automatically start and open the file in Chrome so that I can debug it.
Could you please tell me how to realize this easily?

I want to view the page in an external browser, so I don't need the preview within VS Code.
However, to open the URL specified in the "url" in launch.json, I need to start the server beforehand, and for that I need to show the Live Preview.
Also, the port number may change. Even if I have set the port number to 3000 in the extension settings, the server may actually be running on port 3002 or 3003, in which case I need to rewrite the launch.json file.
I think this is because the previously started server has not been shut down and port 3000 is still in use. I would like the server to also shut down and release port 3000 immediately after debugging is finished.

If this can be achieved by writing launch.json or tasks.json, could you please provide a sample?
Also, if this kind of behavior is not currently supported, I would like you to add the necessary functionality to the extension.

Thanks.

**Comment by andreamah** [comment]
You can run `Live Preview: Show Debug Preview (External)`. This will open a preview outside of your vscode window and the debugger will attach automatically.
