### ISSUE TITLE
Function prints on path on embedded preview

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode-livepreview#266]
Originally from https://github.com/microsoft/vscode-livepreview/issues/143#issuecomment-1098875424
[@falco467](https://github.com/falco467)
> Hi! The current version seems even more broken. When I start live preview in a Workspace I get the following error message on the HTML preview:
> 
> File not found
> The file "\c:\Workspace\myproject\function (old_index, new_index) { \ Shortcut helper to move item to end of array if (-1 === new_index) { new_index = this.length - 1; } if (new_index >= this.length) { var k = new_index - this.length; while (k-- + 1) { this.push(undefined); } } this.splice(new_index, 0, this.splice(old_index, 1)[0]); return this; \ for testing purposes }\index.html" cannot be found. It may have been moved, edited, or deleted.
> 
> It seems there is some Javascript code, which is not evaluated, but gets put directly into the URL.

**Comment by aolszowka** [comment]
This is an older bug, but I am seeing a similar message in https://github.com/benc-uk/armview-vscode/issues/54 its unclear but I believe that this visualization is built on top of `livepreview`. Can you indicate where that code snippet is coming from? What's strange is I see it on some Visual Studio Code installs; but not all?

**Comment by andreamah** [comment]
Where does it say in that extension's source code that it uses Live Preview? It looks like it just uses a vscode webview.

**Comment by aolszowka** [comment]
Apologies; I made a terrible assumption that Live Preview and the WebView were one in the same!
