### ISSUE TITLE
Why is node 14+ required?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-livepreview#267]
Testing https://github.com/microsoft/vscode/issues/158835

I noticed this in the readme: https://github.com/microsoft/vscode-livepreview#prerequisites

> To use this extension, you must have [Node JS v14+](https://nodejs.org/en/download/).

Isn't the node shipped with VS Code sufficient here? Was this only for development in which case it could be moved to CONTRIBUTING.md?

**Comment by andreamah** [comment]
oops, yes, that should be in CONTRIBUTING.md
