### ISSUE TITLE
livePreview.tasks.browserPreviewLaunchServerLogging feedback

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-livepreview#270]
Testing https://github.com/microsoft/vscode/issues/158835

I may have misunderstood the `livePreview.tasks.browserPreviewLaunchServerLogging` setting but I believe it relates to the `Embedded Live Preview Console` _output channel_. If so, here's some feedback about the setting:

- It includes `.tasks` as a prefix which is misleading unless it actually refers to the tasks feature
- It mentioned "auto-generated task terminal", this would read better as `Whether the Embedded Live Preview Console output channel has logging`
- It's not clear what would show up in the channel if logging was disabled. I wonder if this needs to be configurable at all?

**Comment by Tyriar** [comment]
Similar feedback for `livePreview.tasks.runTaskWithExternalPreview`

**Comment by Tyriar** [comment]
I see the Live Preview: Run Server --verbose task now, it only seems to happen for external preview which I don't understand.

**Comment by andreamah** [comment]
`livePreview.tasks.browserPreviewLaunchServerLogging` actually controls whether the task that automatically launches (when external previews are opened) has logging. When it's set to be off, you see a task like this:

<img width="495" alt="image" src="https://user-images.githubusercontent.com/31675041/186272846-38e9ce6d-33dd-4a4b-80ec-cb59b8026b57.png">

Which doesn't log server traffic.

The purpose of having a task automatically run when the external preview is launched is to make it obvious to the user that the server part of the extension is still running. When just using the embedded preview, we know when the server is no longer being used based on when they close the webview panel; from this, we automatically take care of closing the server a few minutes after they close the webview panel. However, once we launch an external preview in a browser, it's a bit trickier to track when they're done. 

To be honest, going back to some of this stuff, I find that the task part of it isn't that intuitive. How much do users need this automatic task to tell them that the server is open? Perhaps if someone really needed the port back, they could just close the server via the command. The task could just be for logging when the user wants to see logging. Also, the reason behind having a task that doesn't log server traffic seems a little meaningless.

Thoughts?

**Comment by Tyriar** [comment]
I see, what if you just register different output channels for each port? Or alternatively, when you click the ports status bar item it gives you a command there to access the server logs? The status bar item already does the job of showing the server is alive imo.

**Comment by andreamah** [comment]
what do you mean `different output channels`? I have different tasks for each workspace that run server logging for different roots, is that what you mean?

**Comment by Tyriar** [comment]
As in new entries per item in the output panel:

![image](https://user-images.githubusercontent.com/2193314/186415061-50e5b188-d213-41ca-b798-325a0584312b.png)

These are just suggestions, we'd probably be best to follow live server's example here. The logs don't seem important at all to me personally so I'd prefer to hide them. We could also hide a "show output" next to the toggle devtools pane entry in the hamburger menu?

**Comment by andreamah** [comment]
Oops, sorry, I think that's there's a misunderstanding. The settings you discussed in your initial comment have nothing to do with the console.logs appearing in the output tab and it has to do with the tasks that are run. Therefore this server _traffic_ logging task is just run as a task.

**Comment by Tyriar** [comment]
Yeah I misunderstood at the start. You can close this off if there's nothing useful here 👌

**Comment by andreamah** [comment]
yeah, I might close this off for now, but I'll probably keep an eye out for a better way to handle all of the task stuff so it's more clear from the start.
