### ISSUE TITLE
livePreview.notifyOnOpenLooseFile is not respected when navigated to manually

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-livepreview#271]
Testing https://github.com/microsoft/vscode/issues/158835

Repro:

1. Open live preview on an html file in the workspace
2. Navigate manually to an absolute path, for example: `http://127.0.0.1:3000/c:/Github/Tyriar/xterm.js/demo/test.html`

🐛 no notification

Expected:

![image](https://user-images.githubusercontent.com/2193314/186215379-bed65aa3-200f-48b4-846c-5c906c172283.png)

**Comment by andreamah** [comment]
Did you previously dismiss the warning? It only warns once per extension run (once per extension activation). I can't quite see how you could have started up the out-of-workspace file server without have seen that warning already, which probably means that you dismissed it already?

**Comment by Tyriar** [comment]
I reloaded the window immediately before the repro steps as I know it only shows up once per session

**Comment by andreamah** [comment]
Ohh you were using the current port to navigate to an absolute path. Absolute paths should only be hosted on its own server, this is a bug.

**Comment by andreamah** [comment]
verif steps:
- open server at root of a workspace
- try to navigate to an absolute path (in your workspace) using the address bar on the embedded preview.
- it shouldn't be available.
