### ISSUE TITLE
Do not activate on onLanguage:html

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-livepreview#272]
Testing https://github.com/microsoft/vscode/issues/158835

I think this activation event is too aggressive and will cause the extension to load a lot of the time when it doesn't end up getting used.

**Comment by andreamah** [comment]
Good point. I originally thought I did that because I wanted the preview icon to appear on the top right corner of the editor when it was on an HTML file, but it seems to do that even without activation event.

**Comment by Tyriar** [comment]
Yep, the activation is just about when the `activate` call in the code runs, all the package.json stuff gets loaded in before activating

**Comment by andreamah** [comment]
for verifier -> use this version of live preview:

[ms-vscode.live-server.0.2.14.zip](https://github.com/microsoft/vscode-livepreview/files/9410966/ms-vscode.live-server.0.2.14.zip)
