### ISSUE TITLE
Open Automatically on Server Start does nothing when the extension isn't activated

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-livepreview#273]
Testing https://github.com/microsoft/vscode/issues/158835

Repro:

1. Close all editors
2. Reload window
3. Right click a html file in explorer and select "Open Automatically on Server Start"

Nothing happens

`onCommand:livePreview.setDefaultOpenFile` should be an activation event

**Comment by andreamah** [comment]
I see, that's intended to just set the path for where to go when you actually start the server, but it makes sense that you'd expect it to also open the preview.

**Comment by Tyriar** [comment]
@andreamah oh no, I expect it to write the path in settings but it does not because the extension does not activate. This is a bug with the fix being adding `onCommand:livePreview.setDefaultOpenFile` to activation events

**Comment by andreamah** [comment]
ah ok that totally makes sense.
