### ISSUE TITLE
Open Automatically on Server Start should use a path relative to the workspace root

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-livepreview#274]
Testing https://github.com/microsoft/vscode/issues/158835

When using this command I see this got written to the workspace settings.json:

```
	"livePreview.defaultPreviewPath": "c:\\Github\\microsoft\\vscode\\test\\leaks\\index.html"
```

This isn't portable and the workspace settings.json is typically committed. Instead it should have set: `test\\leaks\\index.html`

**Comment by DonJayamanne** [comment]
I still see the fully qualified path on my Mac

**Comment by andreamah** [comment]
@DonJayamanne were you in a workspace and previewing a file in your workspace?

**Comment by DonJayamanne** [comment]
I was in a multi root workspace

**Comment by connor4312** [comment]
What's the "this command" that causes the setting to be written? I don't see anything when just previewing a random file in a multi-root workspace.

**Comment by andreamah** [comment]
<img width="491" alt="image" src="https://user-images.githubusercontent.com/31675041/221037691-77e51575-0bb8-4054-a73b-ed6c832d4683.png">

If you select `Open automatically on server start` when you right-click an html file, the corresponding path for `livePreview.defaultPreviewPath` in your workspace settings should be a relative path.

<img width="689" alt="image" src="https://user-images.githubusercontent.com/31675041/221037974-74536e2f-ae44-4e5c-85ff-4b91c3c6835d.png">
