### ISSUE TITLE
Standardize on / for paths in settings

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-livepreview#275]
Testing https://github.com/microsoft/vscode/issues/158835

I see this is the value that is filled in by the extension on Windows:

```
"livePreview.defaultPreviewPath": "c:\\Github\\microsoft\\vscode\\test\\leaks\\index.html"
```

Typically for cross-platform paths we use `/` as the separator as it looks much nicer and is more portable (`\` on unix is not a path separator), with https://github.com/microsoft/vscode-livepreview/issues/274 this would look like:

```
"livePreview.defaultPreviewPath": "test/leaks/index.html"
```

**Comment by andreamah** [comment]
verif steps:
1. Use Live Preview prerelease
2. Right-click an html file in the explorer and click "open automatically on server start"

<img width="255" alt="image" src="https://user-images.githubusercontent.com/31675041/214918997-4a8863f4-33b6-4e13-9be5-2cff14d48721.png">

3. Check the path in `livePreview.defaultPreviewPath`. Should use `/` delimeters.
