### ISSUE TITLE
Terminal task title is very long

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-livepreview#278]
Testing https://github.com/microsoft/vscode/issues/158835

My typical terminal tab width is somewhere around here:

![image](https://user-images.githubusercontent.com/2193314/186223567-26e0f0fb-b89b-4c40-9566-d0be5603f460.png)

Have you considered shortening the title from

```
Live Preview: Run Server --verbose (folder)
```

To something like this?

```
Live Preview: folder
```

**Comment by andreamah** [comment]
That seems better. I was just concerned that there would be no way to see which configuration (`--verbose` or not) you ran it in. Are users usually concerned about that?

**Comment by Tyriar** [comment]
@andreamah It's not clear what `--verbose` maps to anyway, is that a CLI arg you pass to the actual server behind the scenes? Does it map to `livePreview.tasks.browserPreviewLaunchServerLogging`, if so that's very confusing. I don't think knowing verbose is important, but it's also confusing in its current state imo.

**Comment by andreamah** [comment]
`--verbose` is an arg that gets passed to the server. When running from Run Task, you can see the following options:
<img width="277" alt="image" src="https://user-images.githubusercontent.com/31675041/186277620-80bcce4d-10d6-4610-9467-c4c548a93433.png">

`livePreview.tasks.browserPreviewLaunchServerLogging` determines which of these tasks is run automatically when the external browser is run. Setting it to true will run the `--verbose` one.

**Comment by andreamah** [comment]
I think another concern on my side is that, as far as I know, the tasks terminal name is the same name that is seen when you run `Run Task`, which means that omitting info like args will make it indistinguishable from others.

Also, another concern: if I explicitly add the folder name in the name, it would make the option in `Run Task` look strange because the root would show in the description of the quickpick option too:
<img width="247" alt="image" src="https://user-images.githubusercontent.com/31675041/186278113-b4669f83-f296-41b7-964d-bae3577ee491.png">

**Comment by Tyriar** [comment]
@andreamah if it's based on the `livePreview.tasks.browserPreviewLaunchServerLogging` setting, the user doesn't need to know about the default behavior as they are already aware. The setting should typically be a set one and done thing, so I'd argue it doesn't matter for the opening the default one. 

As for this:

![image](https://user-images.githubusercontent.com/2193314/186418234-da134288-3efd-4ca9-84fd-fe847b3fb640.png)

What if the non-default was called out specially here? So if `livePreview.tasks.browserPreviewLaunchServerLogging` was true you would have:

```
Live Preview dir-level-1
Live Preview (no logging) dir-level-1
```

And if it was false:

```
Live Preview dir-level-1
Live Preview (with logging) dir-level-1
```

This optimizes for the primary case that I would assume 95%+ of users would be using

**Comment by andreamah** [comment]
> @andreamah if it's based on the livePreview.tasks.browserPreviewLaunchServerLogging setting, the user doesn't need to know about the default behavior as they are already aware. The setting should typically be a set one and done thing, so I'd argue it doesn't matter for the opening the default one.

I'm a little confused on this. Are you suggesting that I remove the setting and replace it with one that denotes an overall default task for live preview?

**Comment by Tyriar** [comment]
@andreamah I mean keep the setting, but annotate only the non-default with the additional information. Most users will likely not configure anything at all, which means they have a very long title with "--verbose" in it for nothing.

**Comment by andreamah** [comment]
oh I see! that's a good point.

**Comment by andreamah** [comment]
verif steps
1. Install Live Preview prerelease
3. `Run Task` in command palette, then select `Live Preview`
4. Should only have one option (per workspace) called `Run Server`
