### ISSUE TITLE
Support stopping individual servers

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-livepreview#279]
Testing https://github.com/microsoft/vscode/issues/158835

Clicking this:

![image](https://user-images.githubusercontent.com/2193314/186224024-87be3462-fb4d-401e-a8ce-6bf60ebfd978.png)

Results in:

![image](https://user-images.githubusercontent.com/2193314/186224057-bb02ce3d-dbeb-41ec-b47b-d90e87d75dde.png)

I was expecting something like:

- Stop Server on Port 3000 (<folder>)
- Stop Server on Port 3002 (<folder>)
- Stop all Servers

**Comment by andreamah** [comment]
verif steps:
1. Use pre-release version of Live Preview
2. Open a preview
3. `Live Preview: Stop Server`
4. Should see options to stop individual servers
