### ISSUE TITLE
Live refresh not working in Codespaces

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-livepreview#285]
Starting a server on codespaces doesn't work very well.
1. I first got a content blocked page with just a URL of `/`.  Re-opening the page seemed to fix this and give me a valid forwarded codespaces url.
2. Live refresh doesn't work

**Comment by andreamah** [comment]
related to #111

**Comment by andreamah** [comment]
codespaces issues are being covered in #111, this is a known issue
