### ISSUE TITLE
Can not start server

### ISSUE THREAD

**Issue by sao-coding** [microsoft/vscode-livepreview#298]
![image](https://user-images.githubusercontent.com/58339015/186589858-d8cb7135-6201-44d6-acbc-a07f14bed3cc.png)
I don't know how to fix
Reinstall VSCode and Reinstall module
it doesn't work
it stops at opening server

**Comment by andreamah** [comment]
Which version of the extension are you using?

**Comment by sao-coding** [comment]
![image](https://user-images.githubusercontent.com/58339015/187075757-1e2dff41-8eb6-49b1-aaaa-cb7c58f5133f.png)
restart several times
it just works
