### ISSUE TITLE
use "chrome" debug type in created launch configuration

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-livepreview#299]
Testing microsoft/vscode#158835

When running the "Debug Preview" action in a multi-root workspace:

![2022-08-25_14-57-23](https://user-images.githubusercontent.com/1898161/186670772-36ed605f-45d3-44fc-a526-4831e303db48.png)

the generated debug configuration was using "pwa-chrome", which results in a warning:

![2022-08-25_14-49-28](https://user-images.githubusercontent.com/1898161/186670081-6196db9e-f486-47a6-9924-35e953bf255f.png)

As suggested we should use "chrome".

**Comment by andreamah** [comment]
Seems to use `chrome` now.
