### ISSUE TITLE
On which "root" does the "Show Debug Preview" action operate?

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-livepreview#300]
Testing microsoft/vscode#158835

I don't understand on which "root" (or "server") the "Show Debug Preview" actions works.

When I'm editing "root2/index.html" in the editor and then run "Show Debug Preview" action, I would expect that the external browser opens on "root2". But that is not always the case.

**Comment by andreamah** [comment]
"Show Debug Preview" should open on the same URL that the embedded preview opens on. If you have a file in a root called `root2` and it has a file called `index.html` as an immediate child, then the preview should open at `http://127.0.0.1:<port>/index.html`. If the address it goes to keeps changing, this is a bug and some repro steps would be appreciated :D
