### ISSUE TITLE
Closing the browser window never terminated the server-logging terminal task

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-livepreview#301]
Testing microsoft/vscode#158835

> Any time that an external preview is opened (with or without debugger), a server-logging terminal task should run automatically. In this case, the server should stop if the user closes the window or terminates the task.

"Closing the window" never terminated the server-logging terminal task

**Comment by andreamah** [comment]
Ah, I'm not sure why I typed that. I think I meant to say that the server automatically (eventually) stops if you have the embedded preview open only and close it.

**Comment by andreamah** [comment]
I changed the wording in the original issue just in case anyone looks back at it. Thanks for pointing it out!

**Comment by weinand** [comment]
Hmm, for the "embedded preview", I do not see any server tasks in the "Terminal".
But I'm still able to connect to the URL shown in the embedded web view, even after having closed the embedded view.
So it seems that the server is still running...

**Comment by andreamah** [comment]
yup! The server task only runs automatically when you launch an external preview. The server is still running, though. It's a little confusing, but the task only exists to log traffic and/or remind the user that the server is still running if they open an external browser.
