### ISSUE TITLE
Add copyright headers to all files

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode-livepreview#314]
Files don't have copyright headers.

> All of your source files need copyright headers at the top, I didn't notice that before: https://docs.opensource.microsoft.com/releasing/maintain/copyright-headers/

https://github.com/microsoft/vscode-livepreview/pull/309#discussion_r957913427

**Comment by rzhao271** [comment]
Shouldn't the JS files also have the headers?

**Comment by andreamah** [comment]
> Shouldn't the JS files also have the headers?

yup!
