### ISSUE TITLE
Option to specify a default url

### ISSUE THREAD

**Issue by roipoussiere** [microsoft/vscode-livepreview#317]
I have a local server that serve a web page that I need to watch when coding.

I would like to configure VSCode to set its url (ie. `http://127.0.0.1:5000`) and then automatically open this address when opening the live preview, instead of manually set the url each time.

Optionally, an other option to hide the address bar (which is not used in my use-case, since it's always the same) will be greatly appreciated.

**Comment by andreamah** [comment]
You can set the default host to use in the `livePreview.hostIP` setting and the port in the `livePreview.portNumber` setting. In your case, `livePreview.hostIP` should already by `127.0.0.1` by default, so you just would set the default port number to 5000 and it should automatically use this address to host every time.

**Comment by roipoussiere** [comment]
Thank you!
