### ISSUE TITLE
Live Preview stopped working

### ISSUE THREAD

**Issue by palacinka** [microsoft/vscode-livepreview#319]
Live Preview suddenly stopped working

1. nothing happens when executing:  Start Server  or  Show Preview (internal browser) ![image](https://user-images.githubusercontent.com/17987209/187752349-02920f98-0c68-427c-bd42-c61eefbf7b25.png)
2. extension is missing from status bar
![Code_Fp7M8GjIDT](https://user-images.githubusercontent.com/17987209/187751546-8ecae6c1-45c8-407b-94ed-2db07e1a1d74.png)

3. when executing Live Preview (External Browser)  external browser starts with right ip:port but server is not started
4. there is zero related output in any terminal output window ?
5. I tried to remove and re-add extension and close/reopen vscode - did not help
6. Extension worked just fine for few weeks

**Comment by palacinka** [comment]
I think I found the problem.  Looks like web server used by live preview blocked more than 18 ports  between 3000 and 3018  which are now not properly tracked by Windows OS  as I cannot see them at all in netstat or anywhere else... When I try to bind to any of that ports with python socket I  get  `OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions`

After changing Live Preview port to something higher like 3033 it works
`netstat -na|findstr "3033"`
`  TCP    127.0.0.1:3033         0.0.0.0:0              LISTENING`


same netstat command does not find anything for any of 18+ mentioned ports

**Comment by andreamah** [comment]
Hmm. Did you click the preview button once or multiple times when trying to preview? Does your repro look like:
1. open editor on html file
2. click preview button once
3. it opens 18 ports (?)

**Comment by andreamah** [comment]
Just wondering if it's linked to #263

**Comment by palacinka** [comment]
No, those ports are "blocked" and cannot be accessed and Live Preview silently fails as described in my first post. 

I am not sure why those ports are not being seen in netstat  but looks like it may be related to reserved ports by system when using Hyper-V + Docker + WSL2

for clarification it was 16 ports not 18 ports

```
netsh int ipv4 show excludedportrange tcp

Protocol tcp Port Exclusion Ranges

Start Port    End Port
----------    --------
      1324        1423
      1824        1923
      2917        3016
      3121        3220
      3221        3320
      3321        3420
      3421        3520
     10157       10256
     10257       10356
     49671       49770
```

Now I realized it started happening after I installed docker for desktop with WSL2 integration

**Comment by andreamah** [comment]
Sorry for the late follow-up, but does this still happen? And if you just run a basic http server (ie: https://www.npmjs.com/package/http-server) with forwarded ports, does the same happen?

**Comment by andreamah** [comment]
Please create a new issue for this, as this is not the same as the above issue.

Are you using some type of library to run this? This is just for simple web projects. I see that you have some special syntax to link the stylesheet, which might require some extra logic to actually preview the page (which running in the terminal will do).
