### ISSUE TITLE
Bug when previewing UNC files

### ISSUE THREAD

**Issue by ruudhanegraaf** [microsoft/vscode-livepreview#326]
When you try to preview a file opened from a UNC network path, the extension shows a 'File not found error'.

For example, when previewing a file \\\\fileserver\folder\subfolder\something.html, you'll get:

> ### File not found
> The file "**\fileserver\folder\subfolder\something.html**" cannot be found. It may have been moved, edited, or deleted.

(Note the single backslash at the start instead of a double backslash.)

The address bar will display http://127.0.0.1:3000/fileserver/folder/subfolder/something.html as its location.
However, when I change the address to...
http://127.0.0.1:3000/\\fileserver/folder/subfolder/something.html
... it will successfully open the file and all features seem to work.

Kind regards,
Ruud

**Comment by ruudhanegraaf** [comment]
Hi Andrea,

Weird... 🤔

Yep. Still the same I'm afraid. Running 1.74.0 on multiple computers (Windows 11 and Windows 2016).

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/48607712/207129961-b142d024-4cae-4ac8-90c1-7be443711d98.png">

When I add \\ to the address bar in the preview window:

<img width="1214" alt="image" src="https://user-images.githubusercontent.com/48607712/207130059-204fab62-9851-47d0-a088-6c92d8463b5e.png">

In this case I used the IP address, but the same thing happens with both the hostname and the FQDN.

Regards,
Ruud

**Comment by andreamah** [comment]
In this case, is \\10.34.4.183 the server name for the UNC path?

**Comment by ruudhanegraaf** [comment]
Yes and no. :-)
It's the IP adress of the server, which I accessed as \\10.34.4.183.
But the same thing happens when I access it as \\servername or \\servername.company.local.
I just used the IP address for the images so I would not have to blur out any potentially sensitive company information. ;-)

**Comment by andreamah** [comment]
Ah ok I can see the bug now! You were opening a file that is on a server without opening up a workspace folder first, right?

**Comment by ruudhanegraaf** [comment]
Cool! 🙂
But I did (and do) have a workspace folder opened. Not in the situation on the images, but in my normal configuration, I have a workspace opened. 🤔

<img width="636" alt="image" src="https://user-images.githubusercontent.com/48607712/207384836-94104790-bf5f-4bb7-8d88-7035455336d9.png">

**Comment by andreamah** [comment]
Ah, where is the root of the workspace located? Is your preview file inside of the workspace? Is it multi-root? Which extension version are you using?

**Comment by ruudhanegraaf** [comment]
In my work environment, my root is located on a mapped networkdrive. At home - where I have the same problem - it is located on my local hard drive. I also tested what would happen if I copied the file to my network drive and then opened it through the corresponding UNC path, but the same thing happens. That was a multi-root workspace, but I can test it again with a single root. 

Version:

Name: Live Preview
Id: ms-vscode.live-server
Description: Hosts a local server in your workspace for you to preview your webpages on.
Version: 0.4.4
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.live-server

**Comment by andreamah** [comment]
Ah ok. So then, in which cases is `test.html` a child of the current workspace(s)? I can see this happening if it's not a child of the current workspace(s), but I'm confused on why it's happening when it is.

**Comment by ruudhanegraaf** [comment]
I tested some more, and you're right. It works as long as the file is part/child of the workspace you have open. When you asked if I had opened a workspace folder first, I assumed you meant *any* workspace folder. 🙂

_"I also tested what would happen if I copied the file to my network drive and then opened it through the corresponding UNC path, but the same thing happens."_
That didn't work because I had the workspace opened through the mapped network drive and opened the preview file by using CTRL+O and the UNC path. 🤪

But there are times when you want to change a single HTML file, which is not part of a workspace, so it would be nice if it would also work for single, workspaceless files.

**Comment by andreamah** [comment]
> I tested some more, and you're right. It works as long as the file is part/child of the workspace you have open. When you asked if I had opened a workspace folder first, I assumed you meant any workspace folder. 

Ah yes, that's confusing, sorry about that! 

> But there are times when you want to change a single HTML file, which is not part of a workspace, so it would be nice if it would also work for single, workspaceless files.

Yeah, for sure! This is a bug, since workspace-less preview for non-UNC is already supported. Thanks for working through this with me! 😊

**Comment by ruudhanegraaf** [comment]
You're welcome. And ditto. Thank *you* for the support. I'm glad you got to the core of the issue so fast. 🙂
