### ISSUE TITLE
Add setting to toggle CORS

### ISSUE THREAD

**Issue by gjoseph92** [microsoft/vscode-livepreview#332]
Live Preview doesn't currently seem to set the `Access-Control-Allow-Origin` header. This is a reasonable default, but it can sometimes be useful to allow CORS requests. Having a setting to allow this would be helpful.

**Comment by andreamah** [comment]
Hi! What would this be useful for? Is it for loading content hosted by live preview on other domains?

**Comment by gjoseph92** [comment]
@andreamah yes exactly. As a specific example, I was embedding a [Vega-lite](https://vega.github.io/vega-lite/) spec, which accessed CSV files I had stored locally, into an HTML page I was viewing through Live Preview. That worked fine, but when I was having trouble with Vega-lite, I wanted to debug it in the [Vega online editor](https://vega.github.io/editor/#/custom/vega-lite) by just copy-pasting the same spec in. Since the Vega editor is hosted on `vega.github.io`, the cross-origin requests to `localhost:5000` for the CSV files were rejected.

I ended up running [`http-server --cors`](https://www.npmjs.com/package/http-server) alongside Live Server to serve the CSV files. It just would have been more convenient if Live Server had an "Allow CORS requests" checkbox I could have clicked.

**Comment by andreamah** [comment]
Thanks for letting me know! I don't think that it's in-scope for live preview for its server to be accessed from external clients. Plus, it might introduce security issues to allow calls to external clients (since the server accesses the filesystem).

**Comment by bldrvnlw** [comment]
I have the same use case as @gjoseph92 . It would be great if you could revisit this. Regarding security - simply don't set `Access-Control-Allow-Origin` by default but make it an option. If necessary set a warning in the setting document so that those using it will be aware of the risks if they are not already.
