### ISSUE TITLE
Allow Project Servers (NodeJS, Apache, ...)

### ISSUE THREAD

**Issue by hutiwephy** [microsoft/vscode-livepreview#336]
Currently I cannot access my own project ports because it says, "Externally hosted links are not supported in the embedded preview" and it is a really annoying having to swap between browser and VSCode.

So please add some sort of debug whitelist to allow access to NodeJS, Apache and any other type of servers that are intended to be debugged

**Comment by andreamah** [comment]
I believe this is a duplicated of #187. Simple browser (described in the linked issue) should be what you're looking for.
