### ISSUE TITLE
Port reported is incorrect

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-livepreview#34]
1. Start a process on port 3000
2. This causes live server to go to 3001
3. Live server shows a notification saying server started on 3001
4. 🐛 Server is actually on 3002

<img width="750" alt="Screen Shot 2021-06-30 at 1 39 18 PM" src="https://user-images.githubusercontent.com/4544166/124007002-ea165f80-d9a8-11eb-8c71-d647ed464737.png">

**Comment by lramos15** [comment]
Can't get this dialog to appear anymore since I've uninstalled the old one. But what I do notice is this
1. Start a process on port 3000
2. Start live server it goes to 3001
3. Kill the process on port 3000
4. Kill live server
5. Start live server
6. 🐛 Live server picks 3001 and doesn't reclaim 3000

**Comment by andreamah** [comment]
Oh, this is by design so that it doesn't keep retrying ports that were occupied before each time it starts up. I thought it would be more efficient, especially if a lot of ports after the initial port are occupied. I can see that it might be unexpected, though. What do you think about this?
