### ISSUE TITLE
I want to open external websites inside vscode

### ISSUE THREAD

**Issue by muhammadnasr** [microsoft/vscode-livepreview#343]
I want to utilize my Ultrawide monitor and use vscode as browser as well. for ex: I want to open stackoverflow.com or google.com but seems this extension does not support external websites.

**Comment by andreamah** [comment]
Simple browser supports external websites within the editor https://github.com/microsoft/vscode-livepreview/issues/187#issuecomment-1086896479

**Comment by muhammadnasr** [comment]
![image](https://user-images.githubusercontent.com/165384/191809468-8a6c82f3-89b6-4e71-8871-e7a6f3d770e7.png)

**Comment by andreamah** [comment]
That's because, for pages like google, they cannot be shown in an iframe due to cross-origin rules, and we use an iframe within a webview to show website content in Simple Browser and Live Preview. See here for more info: https://stackoverflow.com/questions/8700636/how-to-show-google-com-in-an-iframe

**Comment by muhammadnasr** [comment]
That's what I am talking about.
All external websites (google.com, stackoverflow.com, ...) cannot be open
either in liverpreview or simple browser

We need to have these features, we need to have a real browser inside
vcode, that way developers can open vscode full screen on ultrawide
monitors and use it for coding, debugging and browsing documentation,
stackoverflow.com and anything else without leaving vscode.

Using an iframe is a very old trick that needs to get rid of.

**Comment by andreamah** [comment]
We're currently not planning to offer that in Simple Browser, since websites like those are not meant to be embedded in other web content/applications. 

In Live Preview, the purpose is to use the server that is offered with the extension, so something like that isn't our focus.

**Comment by brandonhaire** [comment]
@muhammadnasr I am trying to find a solution for the same problem. This was a feature that was present in the deprecated 
[Browser Preview](https://marketplace.visualstudio.com/items?itemName=auchenberg.vscode-browser-preview) and it looks like there are several others that are interested but they want us to use Simple Browser even though it does not solve the problem #187. The only solution I've found is Antfu's [Browse Lite](https://marketplace.visualstudio.com/items?itemName=antfu.browse-lite). It's not perfect, but hope this helps.

**Comment by muhammadnasr** [comment]
@brandonhaire This is great.
It works.
