### ISSUE TITLE
Console -DARK MODE

### ISSUE THREAD

**Issue by starzar** [microsoft/vscode-livepreview#348]
Is DARK MODE possible on Console(DevTools)?

Would save some eye strain .

Thanks

**Comment by andreamah** [comment]
Are you talking about the devtools within VSCode (1)? Or Edge DevTools (2)?

1:
<img width="758" alt="image" src="https://user-images.githubusercontent.com/31675041/193322942-829a43aa-4ef0-4349-b6d6-91153da5e57d.png">


2:

<img width="548" alt="image" src="https://user-images.githubusercontent.com/31675041/193323077-092527ef-6d09-4456-b6c7-908799dcb0a0.png">

**Comment by starzar** [comment]
**_VS-Code Live Preview v0.5.2022091501_**

![bandicam 2022-10-01 09-26-10-388](https://user-images.githubusercontent.com/38550930/193386663-9e65afa2-e45a-407e-b84f-a58310a00196.jpg)

**Comment by andreamah** [comment]
> **_VS-Code Live Preview v0.5.2022091501_**
> 
> ![bandicam 2022-10-01 09-26-10-388](https://user-images.githubusercontent.com/38550930/193386663-9e65afa2-e45a-407e-b84f-a58310a00196.jpg)

I believe that the color of these devtools will be dark if your OS is in dark mode. Have you tried setting your OS to use a dark theme? ie: in Windows 11:
<img width="664" alt="image" src="https://user-images.githubusercontent.com/31675041/196562071-c39a816a-eb18-457a-8368-2fd268fd36f7.png">
