### ISSUE TITLE
support `target=_blank`

### ISSUE THREAD

**Issue by Junaid92123** [microsoft/vscode-livepreview#352]
Hello, When I use any link in my HTML page using target=_blank and in the preview, I click on the link so that the link will open in a new tab, nothing happens, and to preview the linked page, I have to close the preview tab then go to the linked HTML page and preview it manually. This doesn't happen when I use the "Live server" extension and preview on Google Chrome browser...

**Comment by andreamah** [comment]
In the embedded preview, we don't support multiple windows/tabs, but there should probably be some warning when trying to use `target=_blank`

**Comment by andreamah** [comment]
Will track this in https://github.com/microsoft/vscode-livepreview/issues/531
