### ISSUE TITLE
401 Unauthorize error when loading crossorigin JS

### ISSUE THREAD

**Issue by enmanji** [microsoft/vscode-livepreview#359]
After updating to v0.4.2, I get a `401 Unauthorize` error and cannot load crossorigin JS.
I have confirmed that it works up to v0.4.1.
Specifically, we are previewing the following HTML.

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>TITLE</title>
    <script type="module" crossorigin src="/static/lib/foo.es.js"></script>  <!-- Reading faile -->
    <script type="module" crossorigin src="/bar.js"></script>  <!-- Reading faile -->
    <link rel="stylesheet" href="/static/lib/style.css" /> <!-- Reading succeed -->
  </head>
  <body>
    <!-- some contents -->
  </body>
</html>
```

I am aware that the CORS check added in [this commit](https://github.com/microsoft/vscode-livepreview/commit/5d2b60a5959a2655b66e118b7dbbb227f9d26055#diff-5b485e76a1bd9ccda1286d952c9216e561097597af1f4cec95b5c720f91616ddR143) now causes an error.
I think this is because `req.headers.origin` is a hostname with http protocol and `expectedHost` is a hostname only (ex. 127.0.0.1:4000).

Is it possible to fix it? I can correct it on my end.

**Comment by nightlyherb** [comment]
This happens on my machine with the most basic HTML:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>Hello World!</h1>
  </body>
</html>
```

I'm on a x86-64 MacBook, MacOS Monterey 12.6 with Live Preview v0.4.2.

**Comment by unpin** [comment]
I noticed that script fail to load with `net::ERR_ABORTED 401 (Unauthorized)` error only when script's `type="module"`.

**Comment by nightlyherb** [comment]
Thank you for addressing this! 

> Hi! Is there a reason why you need to access the page via `localhost` instead of the host address?

Thankfully no. I just used `localhost` because that is what I have seen more often than `127.0.0.1` in learning resources and it's almost built into muscle memory.

I did get surprised when the behavior of `localhost` and `127.0.0.1` was different and barked up some wrong trees, so thank you for fixing this; At least I now know what happened.

> I believe that the extension navigates to the host by default, so I believe that you're navigating to `localhost` manually?

Yes, that was the case. I often just start the server from vscode and view the page in the browser due to lack of screen estate.

**Comment by enmanji** [comment]
@andreamah Thanks for fixing it so quickly!

**Comment by andreamah** [comment]
@nightlyherb Ah, makes sense! Just fyi, you can use a command to auto-open in an external browser and it automatically navigates to the host IP address (`127.0.0.1` by default) https://github.com/microsoft/vscode-livepreview#external-browser-previewing 🙂
