### ISSUE TITLE
`Open Preview in External Browser` missing when on file focus

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode-livepreview#360]
<img width="363" alt="image" src="https://user-images.githubusercontent.com/31675041/194617278-8de3e5d8-dc6a-4ce9-b1e2-2dae9b0594c6.png">

`Show External Debug Preview` is here, but not the normal one.

**Comment by joyceerhl** [comment]
✅ 
<img width="822" alt="image" src="https://user-images.githubusercontent.com/30305945/198145641-695ac331-3b7e-4349-8611-e4760f77ca4c.png">
