### ISSUE TITLE
start.externalPreview.atFile command/shortcut not working

### ISSUE THREAD

**Issue by TD540** [microsoft/vscode-livepreview#367]
VSCode Version: 1.72.2
macOS 12.6

I'm having issues with my shortcut to open preview in external browser:

```
{
  "key": "alt+cmd+o",
  "command": "livePreview.start.externalPreview.atFile"
}
```

Actually, triggering this from Command Palette doesn't seem to work either.

**Comment by andreamah** [comment]
I'm able to reproduce this issue when the server isn't already running.
