### ISSUE TITLE
CLI for live-preview

### ISSUE THREAD

**Issue by mikoloism** [microsoft/vscode-livepreview#368]
Can We use `live preview` with commonds like this : `npm run live-preview`

and in `package.json` we set scripts

``` json
{
  "scripts": {
      "live-preview" : "live-preview-cli --port 3000 --dir ./"
   }
}
```

There is any CLI available to this?

**Comment by surjithctly** [comment]
This will be a great feature. Currently I have some `--watch` scripts. So, instead of manually opening the server, it would be great if we can incorporate it with `package.json` so the terminal would show the URL we can click on (similar to next.js).

**Comment by andreamah** [comment]
Reviewing this, I think that the current task should be able to fulfill most of the need for running the live preview in the terminal https://github.com/microsoft/vscode-livepreview?tab=readme-ov-file#persistent-server-task-with-server-logging

Please let me know if there are other use cases for a CLI executable for live preview, though. VS Code's way of having an 'executable' action is through tasks, which is what is linked above. I don't want to stray away from what other first-party extensions have unless it is really needed.
