### ISSUE TITLE
Support Cross-origin Isolation

### ISSUE THREAD

**Issue by RReverser** [microsoft/vscode-livepreview#375]
In some scenarios, it's important to configure server headers for code to work at all. One notable example is if project depends on WebAssembly threads, which require server to ship static resources with [COOP/COEP headers](https://web.dev/coop-coep/):

```http
Cross-Origin-Embedder-Policy: require-corp
Cross-Origin-Opener-Policy: same-origin
```

Without those, users will get `SharedArrayBuffer is not defined` error at startup, making it impossible to preview such projects with Live Preview server.

**Comment by John-Dean** [comment]
Seconding that this would be incredibly useful as it impacts SharedArrayBuffers - any ETA on this?

Am I incorrect in thinking it would just be adding these 2 headers to this file?
https://github.com/microsoft/vscode-livepreview/blob/4b8d8236ec3bca7e9113f5cc965381f20333687d/src/server/httpServer.ts#L144

**Comment by andreamah** [comment]
I would prefer not to allow users to change the http headers, since that might cause security risks in the future.

For this case, I prefer to add a setting that adds coop/coep headers when enabled.

**Comment by andreamah** [comment]
For any other use cases for editing HTTP headers, please create a separate issue.

**Comment by RReverser** [comment]
> I would prefer not to allow users to change the http headers, since that might cause security risks in the future.

That doesn't really make sense for a _development_ server IMO.

Any local development server allows configuring headers, redirects, etc. for developer's convenience - what's special about LivePreview to forbid those features here?

**Comment by andreamah** [comment]
Giving this a little bit more thought, I could probably make a custom setting to add/remove HTTP headers. My original concern had to do with security, since settings could technically be overwritten by something else, but I believe that this is covered when someone "trusts" the workspace in the workspace trust dialog. You make a good point in that Live Preview is a dev server and should be customizable as so.

*However*, users should be fully responsible for what happens when they put in bad inputs.

**Comment by RReverser** [comment]
@andreamah Thank you!

**Comment by mbnoimi** [comment]
I noticed this feature has been implemented. From where can I modify the headers?

I was suing Five Server. It fix this issue easily by adding `fiveserver.config.cjs` in project root as [mentioned here](https://github.com/yandeu/five-server-vscode/issues/9#issuecomment-950826530)

**Comment by Msfrhdsa** [comment]
Insert these lines into your setting.json:
```
"livePreview.httpHeaders": {
    "Cross-Origin-Opener-Policy": "same-origin",
    "Cross-Origin-Embedder-Policy": "require-corp"
}
```
"Cross-Origin-Opener-Policy": "same-origin" will be your http headers. These headers will make the SharedArrayBuffer work.

**Comment by JomoPipi** [comment]
> Insert these lines into your setting.json:
> 
> ```
> "livePreview.httpHeaders": {
>     "Cross-Origin-Opener-Policy": "same-origin",
>     "Cross-Origin-Embedder-Policy": "require-corp"
> }
> ```
> 
> "Cross-Origin-Opener-Policy": "same-origin" will be your http headers. These headers will make the SharedArrayBuffer work.

It's not working. Getting `Unknown Configuration Setting` in settings.json and still getting `SharedArrayBuffer is not defined`.
