### ISSUE TITLE
banal links don't work

### ISSUE THREAD

**Issue by alrepin** [microsoft/vscode-livepreview#377]
This one `<a id="tgb" href="javascript:changeStyle()">DAY️️</a>` not opened with message that external links not opened. Oh my God, why!? Do it optional! If I debug my site I want to see all content, don't break my project view!)

**Comment by abonic** [comment]
There are a lot of things wrong with the file that the extension injects when launching the preview - "media\injectScript.js" in extension folder. 

For example, this is clearly the wrong way to iterate through a list of links.

```js
function onLoad() {
...
	const links = document.getElementsByTagName('a');
	for (const i in links) {
		// In embedded preview, all link clicks must be checked to see if the target page can be injected with this file's script.
		links[i].onclick = (e) => handleLinkClick(e.target.href);
		links[i].onmouseenter = (e) => handleLinkHoverStart(e.target.href);
		links[i].onmouseleave = handleLinkHoverEnd;
	}
```

After not having much luck reporting a problem similar to yours (https://github.com/microsoft/vscode-livepreview/issues/226), I was able to fix it for myself with the following change:

```js
function onLoad() {
...
	const links = document.getElementsByTagName('a');
	for (const i of links) {
		i.addEventListener('click', (e) => handleLinkClick(e.target.href));
		i.onmouseenter = (e) => handleLinkHoverStart(e.target.href);
		i.onmouseleave = handleLinkHoverEnd;
	}
```

To solve your case as well, it would be necessary to modify function "handleLinkClick" so that it recognizes that "javascript:..." is not an external link. Something like this:

```js
function handleLinkClick(linkTarget) {
	const host = '${HTTP_URL}';
	if (linkTarget && linkTarget != '' && !linkTarget.startsWith('javascript:')) {
		if (!linkTarget.startsWith(host)) {
			postParentMessage({ command: 'open-external-link', text: linkTarget });
		} else {
			postParentMessage({ command: 'perform-url-check', text: linkTarget });
		}
	}
}
```

**Comment by alrepin** [comment]
> There are a lot of things wrong with the file that the extension injects when launching the preview - "media\injectScript.js" in extension folder.
> 
> For example, this is clearly the wrong way to iterate through a list of links.
> 
> ```js
> function onLoad() {
> ...
> 	const links = document.getElementsByTagName('a');
> 	for (const i in links) {
> 		// In embedded preview, all link clicks must be checked to see if the target page can be injected with this file's script.
> 		links[i].onclick = (e) => handleLinkClick(e.target.href);
> 		links[i].onmouseenter = (e) => handleLinkHoverStart(e.target.href);
> 		links[i].onmouseleave = handleLinkHoverEnd;
> 	}
> ```
> 
> After not having much luck reporting a problem similar to yours (#226), I was able to fix it for myself with the following change:
> 
> ```js
> function onLoad() {
> ...
> 	const links = document.getElementsByTagName('a');
> 	for (const i of links) {
> 		i.addEventListener('click', (e) => handleLinkClick(e.target.href));
> 		i.onmouseenter = (e) => handleLinkHoverStart(e.target.href);
> 		i.onmouseleave = handleLinkHoverEnd;
> 	}
> ```
> 
> To solve your case as well, it would be necessary to modify function "handleLinkClick" so that it recognizes that "javascript:..." is not an external link. Something like this:
> 
> ```js
> function handleLinkClick(linkTarget) {
> 	const host = '${HTTP_URL}';
> 	if (linkTarget && linkTarget != '' && !linkTarget.startsWith('javascript:')) {
> 		if (!linkTarget.startsWith(host)) {
> 			postParentMessage({ command: 'open-external-link', text: linkTarget });
> 		} else {
> 			postParentMessage({ command: 'perform-url-check', text: linkTarget });
> 		}
> 	}
> }
> ```

Your advise was so helpful, thank you very much!

**Comment by andreamah** [comment]
@abonic Apologies for the code quality; I've incorporated your helpful feedback in #386.
