### ISSUE TITLE
Is it possible to dock the Live Preview into my second monitor?

### ISSUE THREAD

**Issue by Vandal166** [microsoft/vscode-livepreview#379]
Hi, is it possible to dock the Live Preview into my second monitor. I have a second monitor and that would be cool if I could move the preview tab into my second monitor, maybe there is this option but I don't know how yet, any feedback ?

**Comment by andreamah** [comment]
Are you thinking of moving the preview out of one VS code instance and into another? Or just moving it out of the editor overall? If you would like to move it around, you can always use the [external preview](https://github.com/microsoft/vscode-livepreview#external-browser-previewing) instead.

**Comment by Vandal166** [comment]
> Ah yes, external preview is that what I needed, guess I missed it when reading thanks!
