### ISSUE TITLE
Disable Image Auto-Refresh...

### ISSUE THREAD

**Issue by claytonbp** [microsoft/vscode-livepreview#380]
Not sure if this is a browser related issue or something that could be managed with Live Preview.

Both HMTL and CSS work great with Live Preview and I tend to leave "livePreview.autoRefreshPreview": "On All Changes in Editor", set.

The only issue I have is after I load an image via CSS:

background: url('...');

The image loads fine in Live Preview, however whatever I type after this, the image just refreshes every time I type.

There are a couple of workarounds I use:

1. Set "livePreview.autoRefreshPreview": "On Changes to Saved Files", however I would like to keep on all changes in editor if possible.
2. Set a background-color command after the background url which overwrites the image, so at least this does not refresh each time. Once I have finished with the CSS, I then re-enable the background url which can be tedious.

Is there anyway to disable the refresh on images?

I'm using an iMac Ventura 13.0.1 (72GB RAM, 8GB Vega Graphics Card) and have set Google Chrome as my default browser.

Clayton

**Comment by andreamah** [comment]
Unfortunately, there's currently no way to do that. Implementing it could likely be pretty invasive into user code if it was offered, so I don't think we would implement this. Thanks for filing the issue, though!
