### ISSUE TITLE
Code-server support for Live Preview

### ISSUE THREAD

**Issue by DyloFi** [microsoft/vscode-livepreview#381]
Hey guys, sorry to bother. Just wondering if it’s possible to get Live Preview working within Code-Server. Any help is greatly appreciated.

**Comment by DyloFi** [comment]
> Does it not currently work with `code-server`? I just tried it with the latest version and it seems to work. What bug are you running into?

I just get a blank white screen instead of it previewing my html files.

**Comment by andreamah** [comment]
could you show me a screenshot of the result and what your setup looks like?

**Comment by DyloFi** [comment]
![3AD3C7B4-F82B-42C3-A4FB-DAB4A9632D7A](https://user-images.githubusercontent.com/78475394/205151817-667cb49f-027f-4421-aca6-b2185c07b898.png)

**Comment by DyloFi** [comment]
Sorry just realised you said you wanna see what my setup looks. I recently realised that VScode added the ability to run a remote instance of VScode. 

I was testing it to see if I could access it on my other devices (preferably an IPad) which I can but the only functionality that I need(Live Preview) doesn’t seem to work correctly.

**Comment by andreamah** [comment]
Ahh I see it now when I try to use the server on another device.

**Comment by DyloFi** [comment]
> Ahh I see it now when I try to use the server on another device.

Thanks bud for taking a look at it for me, super appreciative.

**Comment by jayenashar** [comment]
@DyloFi i got a workaround in https://github.com/microsoft/vscode-livepreview/issues/462#issuecomment-1455890874 which is basically to run a proxy in a remote terminal, so it hits the live preview server on 127.0.0.1

**Comment by andreamah** [comment]
I will close this so that tracking for using remote tunnels to access code-server is tracked in https://github.com/microsoft/vscode-livepreview/issues/462
