### ISSUE TITLE
When using "Developer Tools" in "Show Prieview" menu, will inpect vscode Electron UI.

### ISSUE THREAD

**Issue by ltbers** [microsoft/vscode-livepreview#385]
I think "Developer Tools" need inpect preview Web, not vscode Electron UI

Install Live Preview v0.4.4 and do as sscreenshots can reproduce:
<img width="645" alt="01" src="https://user-images.githubusercontent.com/34003506/206516393-e7b2a204-a66a-490c-b6b3-a1798f39be67.png">
<img width="650" alt="02" src="https://user-images.githubusercontent.com/34003506/206517071-d6271d77-c2a9-46e8-887d-dd0ff05de376.png">
<img width="949" alt="03" src="https://user-images.githubusercontent.com/34003506/206517087-b0a0f9be-49c6-48c1-a166-9accde300ce1.png">

**Comment by andreamah** [comment]
Unfortunately, that's the negative of re-using the devtools console from the core editor. It would likely take quite a lot of engineering work to implement a custom devtools console just for the Live Preview window.
