### ISSUE TITLE
Pressing Cmd and + in mac is magnifying browser content

### ISSUE THREAD

**Issue by dashingsloth30** [microsoft/vscode-livepreview#392]
Hi,

When I try to increase the font size of the editor window using Cmd and Plus on Mac, the editor font size increases, and along with it, the live preview browser contents are also getting zoomed in. 

Is there a way to stop the browser content zoom? 

thanks

**Comment by andreamah** [comment]
Are you talking about when you do `cmd` + `+` or `cmd` + `-` from within vscode? As far as I know, that should zoom in everything in the editor. However, if you're talking about supporting content zoom, that would be in this issue: #113
