### ISSUE TITLE
Live Preview is not showing up 

### ISSUE THREAD

**Issue by paperpiedpiper** [microsoft/vscode-livepreview#404]
Microsoft's Live Server addon is no longer a tick-able option in the status bar right click menu, and only shows up as the "Port:3000" after I start the server using Ctrl-Shift-P and selecting Start Preview Server. My guess is that either an update or the Live Server (Five Server) extension I installed afterwards may have botched some JSON settings lines. 😕

Status bar screenshots:
![image](https://user-images.githubusercontent.com/105975348/210746594-f7676492-9895-4f84-b0d0-f61a944725dc.png)

Tried reinstalling VSCode, reinstalling the extension, tried both pre-release and release versions AND older versions. Nothing works.
I would really appreciate the help.

**Comment by andreamah** [comment]
This is the expected behavior for Live Preview. You may be mistaking this for the "Go Live" status bar item, which is in Live Server.
