### ISSUE TITLE
Support authentication flows

### ISSUE THREAD

**Issue by sfabriece** [microsoft/vscode-livepreview#410]
I'm trying to preview a nextjs application using an oauth2 authentication flow.

It does not seem to be currently supported.

**Comment by andreamah** [comment]
We don't support storing client-side info (ie: tokens for auth). With your use-case, it might be best to just run [the dev server that Nextjs offers](https://nextjs.org/docs/getting-started), since it's a little more complicated than the simple cases that Live Preview is targeted towards.
