### ISSUE TITLE
Pointer Lock issue

### ISSUE THREAD

**Issue by IcyChills** [microsoft/vscode-livepreview#411]
Not sure if there is some setting I don't know about to enable pointer lock.
Code runs fine in browser for "document.body.requestPointerLock();".
No effect on VSCode live preview. Need pointer locking to test a Three.js application.

Can use this code from three.js as a test case.
[Live Example](https://threejs.org/examples/?q=games#games_fps)
[Example Code](https://github.com/mrdoob/three.js/blob/master/examples/games_fps.html)

If I've missed a setting which enable pointer lock in VSCode, please let me know.
Thank you for the extension, working great otherwise.

**Comment by andreamah** [comment]
This is an upstream issue that won't be addressed in the main editor, so it can't be supported in the embedded preview for live preview. See https://github.com/microsoft/vscode/issues/154198.
