### ISSUE TITLE
Preview is styled by other pages in browser

### ISSUE THREAD

**Issue by RichardJohnNowell** [microsoft/vscode-livepreview#418]
When using 'More Browser Options/Open In Browser', the resulting page can become styled by whatever is in the Chrome browser, losing its original styling which is still visible in VS Code. This can be got round by closing all tabs and clearing the cache in Chrome, but still leaves the question of why other styling overrides what is shown originally in VS Code. 'Open in browser' does not necessarily mean 'open in browser with the same styling'.

**Comment by andreamah** [comment]
Thanks for pointing that out! I added a FAQ question for that, but I'll keep the phrasing the same in the extension so that it isn't too long of a title.
