### ISSUE TITLE
Asking to open in browser that is not installed fails silently

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode-livepreview#421]
Repro:
1. Set `livePreview.customExternalBrowser`  to `Firefox` on a computer that doesn't have firefox installed
2. Try `Live Preview: Show Preview (External Browser)`
3. Fails silently :bug:

**Comment by rzhao271** [comment]
I don't see any error, nor do I see any failure message.

**Comment by andreamah** [comment]
Did you see a notif like 
![image](https://github.com/microsoft/vscode-livepreview/assets/31675041/35d18465-5f2a-44a8-9292-14082139ba11)
?

**Comment by rzhao271** [comment]
No. It just adds a "Port: 3000" entry to the status bar. Nothing else seems to happen

**Comment by andreamah** [comment]
which version of `ms-vscode.js-debug-companion` are you running? are there any errors in devtools?

**Comment by rzhao271** [comment]
I get the following devtools error message on Windows 11.
I uninstalled Firefox before attempting to verify this issue.

```
mainThreadExtensionService.ts:81 [ms-vscode.js-debug-companion]Cannot read properties of undefined (reading 'Stable')
$onExtensionRuntimeError @ mainThreadExtensionService.ts:81
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
w @ event.ts:1088
fire @ event.ts:1119
fire @ ipc.net.ts:650
Q.onmessage @ localProcessExtensionHost.ts:583
mainThreadExtensionService.ts:82 TypeError: Cannot read properties of undefined (reading 'Stable')
    at Rt.<anonymous> (c:\Users\raymondzhao\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.js-debug-companion\out\extension.js:12:21370)
    at Generator.next (<anonymous>)
    at i (c:\Users\raymondzhao\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.js-debug-companion\out\extension.js:1:1120)
```

js-debug-companion is on v1.1.1
js-debug is disabled
js-debug-nightly is on v2023.6.2717
Live Preview is on v0.5.2023062101

**Comment by luabud** [comment]
I also can't see the notification. Using:
js-debug-companion  v1.1.1
js-debug v1.80.0
Live preview on v0.5.2023062101

Same logs as Raymond's when toggling Developer Tools.

**Comment by andreamah** [comment]
_Should_ be fixed when https://github.com/microsoft/vscode-js-debug-companion/pull/30 is adopted.
