### ISSUE TITLE
Changing server root does not take effect until server is restarted

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-livepreview#424]
Testing microsoft/vscode#172071

1. Using the setup from microsoft/vscode#172071
2. Open a live preview in editor for `file2.html`
3. Confirm a link to file3 doesn't work
4. Now try setting the server root to `src/`
5. Click on the link again

**bug**
The link is still broken

I can only get the link to work after killing the live server and then restarting it

**Comment by isidorn** [comment]
Also got bitten by this. IMHO this is the biggest issue I encounctered.
