### ISSUE TITLE
Add setting to start server from index

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-livepreview#44]
Would love a setting to designate the index to start the server on instead of right-clicking on a file. In my case my index file is in a source folder (dist) and not named (codicons.html). I could then use this with #43 to automatically starts a server for my [codicons preview page](https://github.com/microsoft/vscode-codicons/blob/main/dist/codicon.html).

The old Live Server extension had a `liveServer.settings.root` which works just like this.

**Comment by misolori** [comment]
Thanks for adding this! I was trying to add this setting but got an error:

<img width="1584" alt="CleanShot 2021-07-09 at 08 45 08@2x" src="https://user-images.githubusercontent.com/35271042/125104298-12314d00-e092-11eb-9f93-7d77203d5432.png">

And when using the "Start server automatically from this file" I get this in my settings:

<img width="655" alt="CleanShot 2021-07-09 at 08 46 32@2x" src="https://user-images.githubusercontent.com/35271042/125104375-2bd29480-e092-11eb-9c83-3aaa39f15cf0.png">

Which wouldn't work as a workspace setting because others who are using the repo would have a different path. Is there any way to make the path accept a relative path like `dist/codicon.html`?

**Comment by andreamah** [comment]
Ah I see! I can look into having it check the path as a relative path (if from the workspace settings).
