### ISSUE TITLE
"Prerequisites" missing in marketplace overview

### ISSUE THREAD

**Issue by JimTheFrog** [microsoft/vscode-livepreview#450]
Not a biggie, but https://marketplace.visualstudio.com/items?itemName=ms-vscode.live-server#prerequisites in the table of contents goes nowhere. Are there no prerequisites? (If so, seems best to delete the entry.) If there are or might be but they're not documented yet, would be good to have a placeholder target for the reference.

**Comment by andreamah** [comment]
Nice catch! Thanks for pointing that out!

**Comment by andreamah** [comment]
Fixed in #451
