### ISSUE TITLE
Upgrade reqiured

### ISSUE THREAD

**Issue by AriCohelo** [microsoft/vscode-livepreview#453]
Hello i’m trying tu use the extension and I get thes message “upgrade required” and no preview o my file. Can you help me?

**Comment by andreamah** [comment]
This is showing if you run the `Live Preview: Show Preview (Internal Browser)` in the command palette?

**Comment by Bunyarit50** [comment]
Hello

**Comment by brettcannon** [comment]
It shows in the external browser on Codespaces for me when I follow the FAQ and navigate from the Ports panel.

![image](https://github.com/microsoft/vscode-livepreview/assets/54418/b4a3178d-4234-4552-be4b-951d983cfddb)

**Comment by brettcannon** [comment]
And this is on the 3001 port (the 3000 port is returning a 401 even when I specify the file to open).

**Comment by andreamah** [comment]
Showing `Upgrade Required` on 3001 is expected since it's the websocket port. 
I believe I've seen the 401 error, which is also reported here https://github.com/microsoft/vscode-livepreview/issues/538. I think codespaces isn't forwarding my ports correctly right now, so it's hard to verify.
