### ISSUE TITLE
Preview no longer works in devcontainer outside of project root

### ISSUE THREAD

**Issue by daulis** [microsoft/vscode-livepreview#464]
Versions:
- This worked in version 0.4.5. This no longer works in version 0.4.6
- Visual Studio Code 1.76.0
- Reproduce on Mac and Windows

To repeat:
- Open a project inside a devcontainer
- Working Example
  - From project root in devcontainer: `curl example.com > index.html && code index.html`
  - `Live Preview: Show Preview (Internal Browser)` - Renders OK
- Broken Example
  - From a folder outside of project root in devcontainer (eg: /workspaces): `cp index.html /workspaces && code /workspaces/index.html`
  - `Live Preview: Show Preview (Internal Browser)` - Does not render. Reports the following HTML error
```
File not found
The file "/workspaces/index.html" cannot be found. It may have been moved, edited, or deleted.
```

**Comment by andreamah** [comment]
This seems to also affect Linux (and likely Mac) local development because it affects paths that start with a `/` and are outside of the workspace.

**Comment by andreamah** [comment]
verif steps: 
1. On a unix system (can be remote), open up an html file that isn't in the current workspace.
2. If you preview it, it should work.

**Comment by daulis** [comment]
@andreamah Awesome. Thank you!
