### ISSUE TITLE
Error on clicking menu button: "Failed to load message bundle. See console for details."

### ISSUE THREAD

**Issue by NickGMcAlpin** [microsoft/vscode-livepreview#465]
When I'm live previewing my code and click on the menu button to see the options that should appear there, I instead get the error: "Failed to load message bundle. See console for details."

- Version: 1.76.1

<img width="566" alt="Error message displayed: Failed to load message bundle. See console for details." src="https://user-images.githubusercontent.com/80169975/224494319-fc814c47-f031-4cab-902d-bc27a06afad8.png">

**Comment by Cutuchiqueno** [comment]
same problem with live preview 0.4.7 installed. Console shows:

![grafik](https://user-images.githubusercontent.com/306064/235690458-d617a873-343a-450f-bfa4-781f34212151.png)

**Comment by andreamah** [comment]
Does this happen on the newest version of Live Preview?
