### ISSUE TITLE
command 'livePreview.start.preview.atFile' not found error

### ISSUE THREAD

**Issue by danmenjivar** [microsoft/vscode-livepreview#475]
Type: <b>Bug</b>

When I try to start Live Preview I get this error, worked fine yesterday.

command 'livePreview.start.preview.atFile' not found

Extension version: 0.4.7
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.74GB (5.42GB free)|
|Process Argv|--crash-reporter-id 91d8ecef-2895-48d4-a281-a675c6bb4a6e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30681850
azure-dev_surveyonecf:30548226
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
vscodeenable:30660116
defaultazurewalk:30687958
pythonms35:30686772

```

</details>

**Comment by andreamah** [comment]
Does this persist when you reload the window? Is the html file inside of an open workspace?

**Comment by danmenjivar** [comment]
It did. However, I think I just resolved it by downgrading to an older version of the extension. Somehow that fixed the problem. I even tried upgrading to the latest version and the problem is no longer there. So maybe the issue is related to a bad install and not the extension.

**Comment by benjaminbilgehan** [comment]
I had the same issue and i tried to install previous versions but all failed and i got this 0.2.13 then it worked. but if i update i get the same message 
command 'livePreview.start.preview.atFile' not found

**Comment by andreamah** [comment]
> I had the same issue and i tried to install previous versions but all failed and i got this 0.2.13 then it worked. but if i update i get the same message command 'livePreview.start.preview.atFile' not found
> 
> https://youtu.be/2urVx2YVRxY
> 
> please see the video

Did you try reloading the window?

**Comment by kingpluginser** [comment]
Reloading the window does not work, I used the method of switching the version of the old brother above, which is too metaphysical

**Comment by andreamah** [comment]
Can you run `Developer: Toggle Developer Tools` when this happens and paste the logs here?

**Comment by danmenjivar** [comment]
I'm reopening this issue since it looks like a lot more folks are having the same problem. 

I've basically resolved to just use v0.2.2 and never update this extension.

For those who are wondering how you can install different versions:
![image](https://user-images.githubusercontent.com/41385232/235776303-2d7dbb05-5691-4b8b-8a6f-b38fca0c7069.png)


And if my log is helpful:
```
log.ts:324   ERR [Extension Host] (node:19292) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
console.ts:137 [Extension Host] (node:19292) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
E @ console.ts:137
log.ts:312  INFO [perf] Render performance baseline is 23ms
notificationsAlerts.ts:40 Error: command 'livePreview.start.preview.atFile' not found
    at S._tryExecuteCommand (commandService.ts:91:26)
    at S.executeCommand (commandService.ts:85:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async L.runAction (actions.ts:192:3)
    at async L.run (actions.ts:183:4)
    at async w.onClick (menuEntryActionViewItem.ts:154:4)
onDidChangeNotification @ notificationsAlerts.ts:40
notificationsAlerts.ts:40 Error: command 'livePreview.start.preview.atFile' not found
    at S._tryExecuteCommand (commandService.ts:91:26)
    at S.executeCommand (commandService.ts:85:15)
    at async L.runAction (actions.ts:192:3)
    at async L.run (actions.ts:183:4)
    at async w.onClick (menuEntryActionViewItem.ts:154:4)
onDidChangeNotification @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:28
invoke @ event.ts:659
deliver @ event.ts:861
fire @ event.ts:822
addNotification @ notifications.ts:204
error @ notificationService.ts:130
(anonymous) @ titleControl.ts:202
invoke @ event.ts:659
deliver @ event.ts:861
fire @ event.ts:822
run @ actions.ts:188
await in run (async)
run @ titleControl.ts:83
onClick @ menuEntryActionViewItem.ts:154
(anonymous) @ actionViewItems.ts:149
```

**Comment by andreamah** [comment]
> Also this extension basically stopped working for me after an update. Worked perfectly before then automatically updated and stopped working. That is when I made opened the initial issue.
Do you mean that you're running into the original issue that you posted? In your comment above (https://github.com/microsoft/vscode-livepreview/issues/475#issuecomment-1472694060), it seemed that it eventually worked when you updated to the latest version?

**Comment by danmenjivar** [comment]
Eventually it stopped working for me again. So I just downgraded to a version that works. Figured someone at Microsoft would fix it in a later update. Just a couple weeks back that I onboarded a new dev, I had them install the old version because they had the same issue. Also looking at the issue tracker I see there is another issue reporting the same problem.

**Comment by andreamah** [comment]
Try this:
1. Run `Developer: Set Log Level` in the command palette and set `Trace`
2. Try running live preview
3. In the bottom panel, check logs in the `Extension Host` channel in the `Outputs` tab

Can you paste the logs here?

**Comment by danmenjivar** [comment]
After I reopened the issue. I tried uninstalling VS Code and reinstalling it with all my extensions. And that fixed the issue. I'm on the latest version of both the extension and the editor and I don't seem to have that problem. I guess I'll close this issue again and unsubscribe from it.
