### ISSUE TITLE
External browser cannot automatically start in wsl

### ISSUE THREAD

**Issue by gtianw** [microsoft/vscode-livepreview#493]
When connecting through extension (`ms-vscode-remote.remote-wsl`), Chrome of Win10 cannot automatically start.
I have to enter the url manually.

The extension (`ritwickdey.LiveServer`) will work fine.

**Comment by gtianw** [comment]
Additional remarks: 
The extension works abnormally when `livePreview.customExternalBrowser` is set to chrome. But work fine when `livePreview.customExternalBrowser` is set to default.
Although the default browser of my system is Chrome.

**Comment by andreamah** [comment]
I think I see this happening when the file isn't in the currently opened folder. Are you seeing it under different circumstances?

**Comment by gtianw** [comment]
The file is in the current workspace. But it's in a subdirectory.

**Comment by andreamah** [comment]
Apologies for the delay. Looking at this again, I think I saw that there was a bug regarding opening external browser paths when it was an out-of-workspace path, but it seems that you're running into something else. 

You see that WSL isn't opening the browser when you set it to be non-default? From my side, I see that it's just opening the default browser regardless (on the newest version). Is that not what you see?

**Comment by andreamah** [comment]
Should be fixed with the fix for https://github.com/microsoft/vscode-livepreview/issues/517. To verify, use the steps here https://github.com/microsoft/vscode-livepreview/issues/517#issuecomment-1608407402 but you must use WSL in the first step.
