### ISSUE TITLE
Reloads page in external browser before typing was finished

### ISSUE THREAD

**Issue by simonferndriger** [microsoft/vscode-livepreview#495]
It probably depends on how fast you are writing. However, it happens 5 times out of 10 that the page refreshes while the last (few) characters are not yet in the new code. So I always get errors because some variables cannot be found because they are missing their last character.

I use an external browser window for the live preview since it is a bit annoying to have the live tab in Visual Studio Code refreshed with (almost) every keystroke while you type javascript.

**Comment by uiolee** [comment]
same issue.

the preview chahnging when i am typing, it's noisy.

also, it will loss a character.

is it possible to preview when on save, not on type?

**Comment by andreamah** [comment]
If you set `"livePreview.autoRefreshPreview": "On Changes to Saved Files"`, in your `settings.json` file, then it will just refresh on save.

Alternatively, if it's refreshing too soon for you, you can increase the number in the `livePreview.previewDebounceDelay` setting. That is the minimum number of milliseconds between refreshes, which should be longer if you want less-frequent refreshing.

**Comment by andreamah** [comment]
Closing this issue for now, since there seems to be existing solutions.
