### ISSUE TITLE
 Files in the Chinese path cannot be previewed, and the console cannot be opened then live-preview in code-server

### ISSUE THREAD

**Issue by smalllady** [microsoft/vscode-livepreview#497]
Files in the Chinese path cannot be previewed, and the console cannot be opened then live-preview in code-server
![image](https://user-images.githubusercontent.com/33916586/232647414-4ea5e71b-2c7a-4984-ae4a-8db46bf012c0.png)

**Comment by andreamah** [comment]
We currently don't have support for code-server yet. Tracking progress on https://github.com/microsoft/vscode-livepreview/issues/462
