### ISSUE TITLE
Internal preview window will only shows blank white page

### ISSUE THREAD

**Issue by jakezz** [microsoft/vscode-livepreview#498]
Type: <b>Performance Issue</b>

I feel like it does this when I accidentally try to load a preview of a tab that is a new file and has not been saved anywere yet so the extensions not able to reference it from wherever it's temp file is at? Only thing I can think of. Restarting my computer used to fix it but now I can't get it to work correctly again.. :(

Extension version: 0.4.7
VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz (8 x 1995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.98GB (10.80GB free)|
|Process Argv|--crash-reporter-id 4bd8d20c-0f67-4d8b-a686-2b20b9276853|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   120	 10892	code main
    0	    86	  2404	   window (undefined)
    0	   157	  5824	   utility-process
    0	    76	  8812	     electron-nodejs ("E:\Users\jakez\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\jakez\.vscode\extensions\pucelle.vscode-css-navigation-1.13.3\client\node_modules\vscode-languageclient\lib\utils\electronForkStart c:\Users\jakez\.vscode\extensions\pucelle.vscode-css-navigation-1.13.3\server\out\server.js --node-ipc --clientProcessId=5824)
    0	   127	 12028	     electron-nodejs ("E:\Users\jakez\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "e:\Users\jakez\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=5824)
    0	    76	 13144	     electron-nodejs ("E:\Users\jakez\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\jakez\.vscode\extensions\dbaeumer.vscode-eslint-2.4.0\server\out\eslintServer.js --node-ipc --clientProcessId=5824)
    0	    82	 14812	     electron-nodejs ("E:\Users\jakez\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\jakez\.vscode\extensions\hex-ci.stylelint-plus-0.56.6\server.js --stdio --clientProcessId=5824)
    0	    74	 14856	     electron-nodejs ("E:\Users\jakez\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\jakez\.vscode\extensions\htmlhint.vscode-htmlhint-1.0.4\node_modules\vscode-languageclient\lib\utils\electronForkStart c:\Users\jakez\.vscode\extensions\htmlhint.vscode-htmlhint-1.0.4\server\server.js --node-ipc --clientProcessId=5824)
    0	    83	  9284	   gpu-process
    0	   188	 10620	   window (index.html - wwwroot - Visual Studio Code [Administrator])
    0	    28	 11128	   crashpad-handler
    0	    42	 13028	   utility-network-service
    0	    98	 13924	   issue-reporter
    0	   100	 14976	   shared-process
    0	    78	  9456	     fileWatcher
    0	    76	 14656	     ptyHost
    0	    79	 15084	   window (undefined)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.html - wwwroot - Visual Studio Code [Administrator])
|    Folder (wwwroot): 156 files
|      File types: html(29) js(28) webp(16) png(12) css(12) jpg(8) woff(7)
|                  woff2(7) jpeg(6) json(3)
|      Conf files: launch.json(1) settings.json(1)
|      Launch Configs: pwa-msedge(2) vscode-edge-devtools.debug msedge;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
89544117:30613380
vscrpc:30673769
pythonsymbol12:30671437
defaultazurewalk:30687958
pythonms35:30701012
pythonfmttext:30716742

```

</details>

**Comment by andreamah** [comment]
Can you send a screenshot? Is it just a preview of a file that hasn't been saved yet?

<img width="816" alt="image" src="https://user-images.githubusercontent.com/31675041/235552336-a900c911-8054-4e53-b1eb-a135c5ad0790.png">

**Comment by jakezz** [comment]
Yes, seems to happen when you try to preview a 'new' file that has not been saved to the project directory yet.

**Comment by andreamah** [comment]
> Restarting my computer used to fix it but now I can't get it to work correctly again.. :(

I'm sort of confused about this statement. Is the unsaved file preview not working now still?

**Comment by andreamah** [comment]
Stale issue, closing for now.
