### ISSUE TITLE
[Question] can you use the vs code terminal to show console entries?

### ISSUE THREAD

**Issue by MateusGaldinoLG** [microsoft/vscode-livepreview#50]
Hello, is there a way to use some terminal from Visual Studio Code to see the console entries from the brower? 

Example:

```HTML
<body>
    <h1>Test</h1>
    <script>console.log('Hello World')</script>
</body>
```

Can you see the "hello world" entry in vs code rather than opening the server in the browser?

**Comment by andreamah** [comment]
You can actually access the devtools for the embedded browser by using the `Developer: Open Webview Developer Tools` command. Here, you can see your `console.log()` statements 😊. 

![image](https://user-images.githubusercontent.com/31675041/125141172-82ab8e80-e0d1-11eb-8b56-70cae1ea0bf8.png)

**Comment by MateusGaldinoLG** [comment]
thank you!
