### ISSUE TITLE
Server side browsing when using livepreview in vscode-server

### ISSUE THREAD

**Issue by MartijnVanAndel** [microsoft/vscode-livepreview#505]
It would be great to be able to browse urls server side when using this extension in vscode-server. 
It provides the possibility to test services of other pods/containers in the same kubernetes environment als VScode. Think of: api's, api documentation and pod front-ends, while these locations are not yet exposed outside of your namespace/kubernetes cluster. 

I'm presuming this extension is using the 'Simple Browser' feature of VScode, to show webpages. 
And I presume this 'Simple Browser' is a client side browser. 

We previously used the 'Browser Preview' extension, which provides the possibility of server side browsing. 
When you run VScode in a kubernetes environment, you can access the web frontends of other pods you are allowed to. 
This makes it possible to test and develop unexposed backend services.

**Comment by andreamah** [comment]
When you say `vscode-server`, do you mean the remote tunnelling functionality? Like described in https://code.visualstudio.com/docs/remote/tunnels.

**Comment by andreamah** [comment]
Stale issue, closing for now.
