### ISSUE TITLE
Does it work with simple watch scripts?

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode-livepreview#51]
Having a minimal project:

```
src/
    css/
        index.css
    scss/
        index.scss
    index.html
package.json
```

<details><summary>package.json</summary>

```json
{
	"name": "playground",
	"version": "1.0.0",
	"scripts": {
		"watch": "npm run sass-watch",
		"sass-watch": "sass --watch src/scss/index.scss:src/css/index.css"
	},
	"devDependencies": {
		"sass": "^1.35.2"
	}
}

```

</details>

</details>

<details><summary>index.html</summary>

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
	<link rel="stylesheet" href="./css/index.css">
</head>
<body>

</body>
</html>
```

</details>

<details><summary>index.scss</summary>

```scss
body {
	background-color: aqua;
}
```

</details>

It fails to refresh on files updated by `sass --watch`.

![demo](https://user-images.githubusercontent.com/9638156/125063766-90a0e580-e0b8-11eb-89a4-d9d93cdbef3e.gif)

**Comment by usernamehw** [comment]
If it can't - would it make sense to allow watch files by glob?

```js
"LivePreview.watchFiles": "src/**/*.{html,css,js}",
```

**Comment by andreamah** [comment]
It doesn't work with watch scripts, but the setting you described in your second comment could be added.

**Comment by usernamehw** [comment]
I'm not sure it works as expected. 

Generated files glob: `src/**/*.{html,css,js}` - it does not update preview on `.scss` file changes.

Generated files + scss file glob: `src/**/*.{html,css,scss,js}` - it updates, but only to the old state the `.css` file was at.

**Comment by andreamah** [comment]
I see now, the preview is updating before the CSS file is updated via the watch script. I will re-open and see if there is a better solution.

**Comment by andreamah** [comment]
This change should be live on the marketplace in `v0.2.3`. To get the best performance, try changing the refresh to be saved files. This way, Live Preview's watcher will respond to the refreshing occurring with `sass --watch scss/:css/`. The default option responds to changes in the editor, which may trigger a refresh too soon and load the old CSS.
![image](https://user-images.githubusercontent.com/31675041/125844045-be11305c-97ef-42e3-a6b8-d60c4ba435a0.png)

Let me know if it works for you!

**Comment by usernamehw** [comment]
It does work now 👍.

**Comment by christophemacabiau** [comment]
Hi @andreamah Sorry but I dont see in the live preview settings the watch files option (I have the last version installed, on linux)

**Comment by andreamah** [comment]
Responded on #233
