### ISSUE TITLE
Triggering live preview using terminal

### ISSUE THREAD

**Issue by smdsayeed** [microsoft/vscode-livepreview#512]
I would be a great feature if the live preview was toggled by just typing "show" as the command in the terminal , which helps to preview the current open page of html  code without even lifting the hands from the keyboard

**Comment by andreamah** [comment]
I likely wouldn't want control from the terminal, since that would only work if you already had VS Code open. Perhaps you could set a keyboard shortcut to one of the Live Preview commands that the extension contributes.

**Comment by smdsayeed** [comment]
Gave a try couldn't found how to? help me with this

**Comment by smdsayeed** [comment]
That's great idea , created a shortcut using TAB + L   It works perfectly fine.👌
