### ISSUE TITLE
Support custom external browser on remote cases (SSH, Dev Container)

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode-livepreview#517]
It seems that, when we want to set `livePreview.customExternalBrowser` in a remote scenario, it can't detect browser locations on the host. 

Looking a little more into this, we'd need some way for the extension to access local executables, which would require a companion extension locally. 

For WSL, we could force it to look for windows paths under `/mnt` as a band-aid solution now.

**Comment by andreamah** [comment]
verif steps:
1. open a workspace in WSL, devcontainers, or SSH.
2. Set `livePreview.customExternalBrowser` to be any browser you have on your system (don't choose `Default`).
3. Run `livePreview.customExternalBrowser`
4. This should open the appropriate browser on your machine.

**Comment by luabud** [comment]
verified with Dev Containers 🥳
![externalbrowser-livepreview](https://github.com/microsoft/vscode-livepreview/assets/45497113/90af6732-21a2-4113-b1e5-4f90097a6b96)
