### ISSUE TITLE
More browsers

### ISSUE THREAD

**Issue by o-t-w** [microsoft/vscode-livepreview#523]
Are there any plans to add any more browsers? I usually use Chrome Canary or Firefox Nightly for development but that isn't listed in the dropdown. Also Safari? 
<img width="905" alt="Screenshot 2023-06-26 at 20 41 35" src="https://github.com/microsoft/vscode-livepreview/assets/29547922/0fdb61e1-8dfa-4dd4-9c5c-cffd1407a71b">

**Comment by andreamah** [comment]
I'll add an extra path field for custom installations here https://github.com/microsoft/vscode-livepreview/issues/514
