### ISSUE TITLE
Show an error message if selected custom external isn't installed

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-livepreview#524]
This is just a suggestion for something that occurred to me as I was verifying https://github.com/microsoft/vscode-livepreview/issues/517

I selected "firefox" first not realizing I didn't have it installed on my machine. It just made the "open externally" command fail silently.

**Comment by andreamah** [comment]
Were you on prerelease? I actually just fixed something like that for #421

It should pop up something like this: 
<img width="423" alt="image" src="https://github.com/microsoft/vscode-livepreview/assets/31675041/76056dca-37cc-42fb-81e1-0c950b458664">

**Comment by andreamah** [comment]
Thinking about this again, do you think that it should be a modal window instead of of a pop-up notification? Perhaps since it's a pretty big error, it should be pretty noticeable.

**Comment by luabud** [comment]
I think making it a model window makes sense to me given it's a blocking action? Don't feel strongly about it though. I can't see the notification unfortunately :( I'll share my logs on the other open issue

**Comment by andreamah** [comment]
That's ok! I think that there was some cases of it not working, as found in #421. I'll close this in favour of that issue, which should be tracking the same thing.
