### ISSUE TITLE
Live Preview is not working correctly

### ISSUE THREAD

**Issue by MohamedGamalElSherbiny** [microsoft/vscode-livepreview#527]
![Screenshot 2023-06-30 at 12 07 14 PM](https://github.com/microsoft/vscode-livepreview/assets/59318400/2cc6f22b-e33d-4d67-906b-2e9881273510)
<img width="1680" alt="Screenshot 2023-06-30 at 12 07 24 PM" src="https://github.com/microsoft/vscode-livepreview/assets/59318400/09b9993f-5758-4b6a-80d4-5128dc9e3dc1">

**Comment by andreamah** [comment]
Did you link your css file correctly? If `Resources` is a folder at the root, try linking it as `/Resources...`

**Comment by MohamedGamalElSherbiny** [comment]
I think there is a problem with bootstrap, because whenever I remove the bootstrap it works fine with the css but when adding it, it shows up like this.

**Comment by MohamedGamalElSherbiny** [comment]
`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EGYPT | Aeronautical Information Management Website</title>
    <link rel="stylesheet" type="text/css" href="./Resources/assets/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>
  <body>

    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <img src="./Resources/images/72pfyckv83-1.jpg" alt="Logo" width="50" height="50" class="d-inline-block align-text-top">
                <h1 class="navbar-brand fonts">Aeronautical Information<br>Management Egypt</h1>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                    <div class="d-flex justify-content-end">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active fonts" aria-current="page" href="#">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link fonts" href="#">Services</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle fonts" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Training
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item fonts" href="#">Instructor</a></li>
                                    <li><a class="dropdown-item fonts" href="#">Trainee</a></li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link fonts" href="#">About Us</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link fonts" href="#">Contact Us</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
  </body>
</html>`

**Comment by MohamedGamalElSherbiny** [comment]
``<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test</title>
    <link rel="stylesheet" type="text/css" href="./Resources/assets/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>
  <body>

    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <img src="./Resources/images/72pfyckv83-1.jpg" alt="Logo" width="50" height="50" class="d-inline-block align-text-top">
                <h1 class="navbar-brand fonts">Title</h1>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                    <div class="d-flex justify-content-end">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active fonts" aria-current="page" href="#">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link fonts" href="#">Services</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle fonts" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Training
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item fonts" href="#">Instructor</a></li>
                                    <li><a class="dropdown-item fonts" href="#">Trainee</a></li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link fonts" href="#">About Us</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link fonts" href="#">Contact Us</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
  </body>
</html>``
