### ISSUE TITLE
Extension host teminated unexpectedly 

### ISSUE THREAD

**Issue by BaltWeb** [microsoft/vscode-livepreview#540]
Type: <b>Performance Issue</b>

Hi,

Please find below a short explaination of the issue encountered:

1. All extensions do not seem to work.
2. I have used VS Code a lot prior to this issue without any problems.
3. I have tried un/installing, dis/enabling various extensions to no avail.
4. I have tried dis/enabling various extensions exiting VSC, again  to no avail.
5. I un/reinstalled VSC only to find the issue persists.
6. During normal operation of VSC, I get a prompt on the bottom right as follows : "Extension host terminated unexpectedly x times with in 3 minutes."  "Start Extension Bisect" which I do to try to resolve the issue but issue continues to persist.

Please let me know your recommendations in order to resolve this problem and continue to use VSC uninterrupted.

Regards

Alex 

Extension version: 0.4.9
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) N5100 @ 1.10GHz (4 x 1114)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|11.75GB (6.73GB free)|
|Process Argv|--crash-reporter-id c815b5d7-39a2-4c81-be78-2df930388f1b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   121	  9688	code main
    1	    90	   612	window [2] (Issue Reporter)
    0	    89	  2952	fileWatcher [1]
    0	    94	  3520	ptyHost
    0	    79	  4896	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\CHUWI\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	    18	  7608	       "C:\xampp\php\php.exe" -S localhost:8888
    0	    75	  5228	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\CHUWI\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	     7	  7484	     conpty-agent
    0	     7	  9780	     conpty-agent
    0	    46	  4348	   utility-network-service
    0	    33	  6100	   crashpad-handler
    0	   165	  9208	window [1] (Running Extensions - demo1 - Visual Studio Code)
    0	    95	 10016	shared-process
    1	   154	 10176	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Running Extensions - demo1 - Visual Studio Code)
|    Folder (demo1): 2 files
|      File types: php(2)
|      Conf files:;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
3biah626:30602489
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30812748

```

</details>

**Comment by andreamah** [comment]
Does this still happen when live preview is uninstalled? If it still happens without live preview, I believe this is a more general vs code problem.

**Comment by BaltWeb** [comment]
Hi Andrea,

Thank you for following up on my issue.

I have been busy on family requirements and was unable to check your
recommendations.

Hope to find time to continue my work tomorrow and fill you in on my
findings.

Kind regards

Alex

**Comment by BaltWeb** [comment]
Hi Andrea,

The extension causing the error in question, detected as shown in
screenshot below :

[image: image.png]

Looking further, I noticed that actually I had not uninstall all my
previous extensions.

With all extensions deleted, I started to reinstall one by one extensions
till the error re-occurred, as shown.

Kind regards

Alex

**Comment by andreamah** [comment]
Hi! the image actually didn't show. what is the extension called?

**Comment by BaltWeb** [comment]
Hi

This one :

DEVSENSE.phptools-vscode

I copied the extension ID.

Also pasted the screen shot on the excel file attached for your reference.

Let me know if you need further information.

Alex

**Comment by andreamah** [comment]
Please file this at https://github.com/DEVSENSE/phptools-docs/issues, as they are the developer behind this extension.
