### ISSUE TITLE
Enable files preview without opening a folder for remote connection

### ISSUE THREAD

**Issue by pilkjaer** [microsoft/vscode-livepreview#543]
I use VS Code in remote mode so I don't have an option to drag-n-drop files like you show in your examples for Workspace-less Previewing. So for me context menu is the only option. Currently the only way for me to activate a live preview is to open a folder in VS Code and then R-Click a file and choose "Show Preview". 
I often have a need to open files from different locations. Currently, if I have a html file open in VS Code i can't just R-Click on it's tab and select "Show Preview" to show it as a webpage. I can't do the same from the Open Editors list either.
It would be nice to integrate plugin into those context menus as well so that remote users can easily preview webpages without a need to open a new VS Code instance with the correct folder just to be able to achieve that.

P.S. After some more playing around with it it seems that you actually can r-click inside of the file and you will get that "Show Preview" option. This is somewhat hidden/non-intuitive. So this change request is more about usability aspect of this.

**Comment by andreamah** [comment]
Are you using the Remote-SSH extension to preview remote files? If so, Live Preview should work there. You should be able to click the preview icon to preview on html files.
<img width="190" alt="image" src="https://github.com/microsoft/vscode-livepreview/assets/31675041/2dbf7f08-537d-4c74-9b60-93df0c50e5a4">
