### ISSUE TITLE
Please add Just Showing Url

### ISSUE THREAD

**Issue by rezaei** [microsoft/vscode-livepreview#545]
Hi , Please add a new feature , that just show URLs ,
and don't start any local server . 
it seems , your extension is not useful for angular development ..

**Comment by andreamah** [comment]
This extension is most useful for projects where a server is not already created (e.g. not for apps using React, Angular, etc.). To work with these, feel free to run the Simple Browser: Show command that is already built-in with VS Code.

**Comment by PGTBoos** [comment]
for angular, most likely you would be able to use ng serve
