### ISSUE TITLE
Codespaces 401

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode-livepreview#546]
previewing a file on codespaces results in a 401 error.

**Comment by andreamah** [comment]
repro steps: 
1. Preview an HTML file in codespaces. You might need to follow the steps in the readme to preview it https://github.com/microsoft/vscode-livepreview#faq
2. You shouldn't get a 401 error; instead, the preview should work.

**Comment by rzhao271** [comment]
I'm getting 404 errors now when I try previewing some HTML files in a Codespace.
I followed the steps in the FAQ and got a preview to show, but the preview is empty.
![Devtools 404 errors](https://github.com/microsoft/vscode-livepreview/assets/7199958/8ca444cc-17fe-44fa-b9ac-e6a3e355818e)

**Comment by andreamah** [comment]
Fixed in new prerelease 0.5.2023092802
