### ISSUE TITLE
 An unknown error occurred.

### ISSUE THREAD

**Issue by Daarka** [microsoft/vscode-livepreview#547]
I've been using this extension since I installed this software about a year ago. It was a core necessity to the software for me. Never had an issue with it, until I launched the app today to test out some simple code for the first time in a while. When I click the button that should have opened the preview, I get an error code popup in the bottom right reading "An unknown error has occurred. Please consult the log for details."

But I'm not sure what log it's talking about. If I open the terminal, none of the tabs have anything to say about this error. If I click the error itself, it doesn't result in any such log opening up. I'm sorry if this is a stupid issue to be having, but I'm a very casual user and don't know my way around this software _extremely_ well, only enough to do the simple things I need it for.

The extension FAQ has a bit about manually navigating to the port links or something, but I also can't find that. I can open the terminal, but there is nothing anywhere within it that mentions ports. 
![Screenshot](https://i.gyazo.com/69a33475fa3e11e5b6df93be8791925c.png)
In the extension FAQ, elsewhere is included a screenshot of a Ports menu. That simply does not exist on my end. I'm unsure if there's something I'm supposed to enable or some other extension I need to install to make that appear. In the "View" menu of the app, nothing seems to be labeled "Port" related that I could potentially unhide.

I've tried both using the current as well as the pre-release version of the extension. I did not voluntarily upgrade any software/extension versions, but it seems like something updated itself and potentially caused an issue that never existed before. I'm not sure what to do when the buttons I'm told to click simply don't exist, and the error popup is as unhelpful as they come.

**Comment by Daarka** [comment]
I have a more savvy friend helping me (or attempting to), and they recommended I share this detail. There is no ports icon on the bottom toolbar (which is where it lives on THEIR version of the app), and right-clicking next to the terminal tab does not bring up anything fruitful either. 
![Screenshot](https://i.gyazo.com/4ab731fe1478dee2b75d8f158d909546.png)

I have a unique curse where whenever I encounter a problem and need to troubleshoot it, the button I must click simply does not exist for no understandable reason :)

**Comment by Daarka** [comment]
Welp, nevermind I guess. I used to be able to start a new file and get the live preview to work even if I never actually saved it; now, it turns out I need to save the file into the designated workspace that VSCode is focused on; once I do that, the live preview will function as normal for any files within that folder. 

The port buttons still don't exist, and seemingly never have on my end 🤡 But at least the extension works now, which is all I care about.

**Comment by Daarka** [comment]
Welp, nevermind I guess. I used to be able to start a new file and get the live preview to work even if I never actually saved it; now, it turns out I need to save the file into the designated workspace that VSCode is focused on; once I do that, the live preview will function as normal for any files within that folder.

The port buttons still don't exist, and seemingly never have on my end 🤡 But at least the extension works now, which is all I care about.

**Comment by Mirrorman95** [comment]
I'm having this exact problem, except that I can see the PORTS menu next to the TERMINAL tab. Live Preview was working fine a few days ago, and then all of a sudden, it just keeps giving me the same error that Daarka had. I tried restarting my computer, uninstalling and reinstalling the extension, switching to other versions of the extension, and I even installed VS Code Insiders version and tried Live Preview in that, but it always just gives me the same error:
`An unknown error occurred. Please consult the log for more details.`
