### ISSUE TITLE
Changing currentTime of HTMLAudioElement requires that Content-Length

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode-livepreview#549]
> Changing currentTime of HTMLAudioElement requires that Content-Length exists in response header.
> ```javascript
> const audio = new Audio()
> audio.ondurationchange = function () {
>   console.log(`ondurationchange: ${audio.duration}`)
> }
> audio.oncanplay = function () {
>   audio.play()
> }
> const playButton = document.createElement('button')
> playButton.innerText = 'play'
> playButton.onclick = function () {
>   audio.src = './FloralLife.mp3'
> }
> const setButton = document.createElement('button')
> setButton.innerText = 'set current time'
> setButton.onclick = function () {
>   audio.currentTime = 20 // require Content-Length
> }
> document.body.append(audio)
> document.body.append(playButton)
> document.body.append(setButton)
> ```

from @toyobayashi

**Comment by andreamah** [comment]
repro steps:
1. paste the above block into `<script> ... </script>` in an html boilerplate. 
2. Adjacent to the file, put an mp3 file called `FloralLife.mp3`
3. ensure that 'play' button plays the song and the 'set current time' button starts the song from 20 seconds in.

**Comment by justschen** [comment]
9.5/10. author did not provide a funny mp3 file, `FloralLife.mp3`
