### ISSUE TITLE
Could not register service worker: InvalidStateError.

### ISSUE THREAD

**Issue by AbelPucela94** [microsoft/vscode-livepreview#551]
Hi. Today, when I opened my VS and then, click on the "show view" on right button, VS said this error: could not register service worker: InvalidStateError. Failed to register a ServiceWorker: The document is in an invalid state.

This document worked perfectly yesterday... ¿why now it's not working anymore? ¿Someone has been the same?? Thanks

**Comment by andreamah** [comment]
Does this happen, even when you reload? Are you on vscode desktop or codespaces?

**Comment by AbelPucela94** [comment]
Already solved! I reloaded the vscode and apparently it has not failed again. Thanks!
