### ISSUE TITLE
Multiple root

### ISSUE THREAD

**Issue by brucey0x** [microsoft/vscode-livepreview#553]
I'm using a /src, /build and /public folder structure for my projects. My /public folder hosts my HTML and CSS files. These are copied into /build upon compiling. However I'd like to be able to run the server from roots in both /public and /build so that the HTML files I'm previewing always have access to my compiled .js files in /build. Does this feature exist? If not, any suggestions for others tools I may be able to use to achieve this?

**Comment by andreamah** [comment]
Is there a reason that you can't have them in the same directory or at least create symbolic links such that you can access them from the same directory?

**Comment by brucey0x** [comment]
Hi Andrea, thanks for checking in. 

How do you mean have "them" in the same directory? I'm working in /src and compiling to /build. The JS isn't accessible in /public only. 

Do you have an example or reference for the symbolic links? I'm unfamiliar with them.

For what it's worth I've been able to avoid running into this issue by using Vite as a build tool, which creates a dev environment and server fluently and avoids me having to handle this manually.

**Comment by andreamah** [comment]
I think I'm a bit confused about your code structure looks. When code in `/public` references code outside of it, how does it do so? Also, does using a multi-root workspace in vscode help?
