### ISSUE TITLE
Ability to show preview panel above the code (and code in panel underneath) instead of side by side?

### ISSUE THREAD

**Issue by natalie-tuckwell** [microsoft/vscode-livepreview#558]
Apologies if this is a very basic question, I would like to see the web page preview in a top panel in landscape, and the VS code below it. The default is side by side which is not ideal for me. Thank you in advance.

**Comment by andreamah** [comment]
You can drag the window to the top of the editor to split it horizontally:

[![Image from Gyazo](https://i.gyazo.com/728cb26078576e7075955302e4556ea7.gif)](https://gyazo.com/728cb26078576e7075955302e4556ea7)

**Comment by yanbo92** [comment]
I want this too, so I build a custom version.
https://github.com/yanbo92/vscode-livepreview-not-split/releases/tag/0.4.13
