### ISSUE TITLE
Error: An unknown error occurred. Please consult the log for more details.

### ISSUE THREAD

**Issue by Mirrorman95** [microsoft/vscode-livepreview#567]
OS: Windows 10 x64
Program Version: VS Code latest build, VS Code - Insiders latest build
Extension Version: Live Preview Release, Live Preview Pre-Release, and older builds

I'm having the exact same problem as #547, except that I _can_ see the PORTS menu next to the TERMINAL tab. Live Preview was working fine a few days ago, and then all of a sudden, it just keeps on giving me the same error that Daarka had. I tried restarting my computer, uninstalling and reinstalling the extension, switching to other versions of the extension, and I even installed VS Code Insiders version and tried Live Preview in that, but it always just gives me the same error:
`An unknown error occurred. Please consult the log for more details.`

How do I fix this?

**Comment by andreamah** [comment]
Are you using it something like remote SSH or WSL? Or are you accessing files on your local machine? If you do `Developer: Toggle Developer Tools` in the command palette, what do you see?

**Comment by Mirrorman95** [comment]
> Are you using it something like remote SSH or WSL? Or are you accessing files on your local machine? If you do `Developer: Toggle Developer Tools` in the command palette, what do you see?
I am accessing files on my local machine, yes.
When I used Toggle Developer Tools like you said, it opened up a console menu very similar to the ones I'd see when opening the web developer tools on Chromium browsers. Then, after trying to run Live Preview again, the Console pane showed me these error messages:
```
[Extension Host] (node:18824) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
w @ console.ts:137
console.ts:137 [Extension Host] Clang Language Server is now active!
console.ts:137 [Extension Host] [vscode-icons] v12.6.0 activated!
console.ts:137 [Extension Host] Unknown error: Error: listen EACCES: permission denied 127.0.0.1:3000
console.ts:137 [Extension Host] Unknown error: Error: listen EACCES: permission denied 127.0.0.1:3001
notificationsAlerts.ts:40 Error: An unknown error occurred. Please consult the log for more details.
	at i.h (e:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:125:140016)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
c @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:28
y @ event.ts:1140
z @ event.ts:1151
fire @ event.ts:1175
addNotification @ notifications.ts:204
error @ notificationService.ts:130
(anonymous) @ editorTabsControl.ts:190
y @ event.ts:1140
z @ event.ts:1151
fire @ event.ts:1175
run @ actions.ts:190
await in run (async)
run @ editorTabsControl.ts:71
onClick @ menuEntryActionViewItem.ts:156
(anonymous) @ actionViewItems.ts:150
```
