### ISSUE TITLE
Prieview processed html file (in another directory).

### ISSUE THREAD

**Issue by oliwerAR** [microsoft/vscode-livepreview#569]
In my settup I have some html files in `app/` directory, which are proccesed (by gulp) and outputted in `dist/` directory.
The gulp settup includes browser-sync preview running on `http://localhost:3000` but it forces me to manually navigate to the speciffic html file.

What I want to achive is when I lunch a preview on html file somewhere in `app/` the preview displays corresponding file from from `dist/` (or from the browser-sync on `http://localhost:3000`).

I tried tinkering with root and proxy setting with no luck.

Please, help!

**Comment by andreamah** [comment]
If browsersync already refreshes a server hosted at localhost, you should consider using the `Simple Browser: Show` command instead to preview your project.

**Comment by oliwerAR** [comment]
@andreamah That deosn achive what I'm after.
Maybe I should clearify. I'm not after opeing just the defualt (index) page under `dist/` / `http://localhost:3000`.
What I want is: 
I'm editing a file, e.g. `app/subdir1/subdir2/subdir3/filename.html` 
and I want to preview `dist/subdir1/subdir2/subdir3/filename.html` or using browser-sync  `http://localhost:3000/subdir1/subdir2/subdir3/filename.html`.

I want to make my life easier bc there is quite a lot of files in many different (multiple level) subdirs and navigating to the prieview manually each time is pain.

**Comment by andreamah** [comment]
There currently isn't a way to say preview one file from another file, even if they're related. If your files are all at the same path, you can always try setting `livePreview.serverRoot` and then just starting a server at that dir and navigating to your file. Or you can try a multi-root workspace with one root closer to your preview files such that you can open the preview easier.

**Comment by andreamah** [comment]
Are aren't any plans at the moment to implement something like this, however. I will close this for now unless more people show interest in this type of feature.
