### ISSUE TITLE
Background blur doesn't work properly

### ISSUE THREAD

**Issue by JamesMinoucha** [microsoft/vscode-livepreview#575]
in css, the parameter "backdrop-filter: blur(20px);" makes a weird effect, here are some images.

Live Preview
![broken blur](https://github.com/microsoft/vscode-livepreview/assets/119378901/5172fa08-4169-40e2-87d0-0dba2e634ff3)

Expected
![normal background blur](https://github.com/microsoft/vscode-livepreview/assets/119378901/504189c0-7429-4d1f-b63b-869ece20d5c6)

**Comment by andreamah** [comment]
Do you have some code for minimal reproducible steps (with code)? How are you previewing the page in your expected screenshot?

**Comment by JamesMinoucha** [comment]
Hey!

The problem has been resolved, thank you very much for doing a really good
job! 😁
It's not often that such minor bugs are fixed.

Best regards!

Le ven. 15 déc. 2023 à 22:37, Andrea Mah ***@***.***> a
écrit :
