### ISSUE TITLE
Live Preview does not work correctly in Codespaces

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode-livepreview#58]
The websocket does not correctly connect at the current version (0.1.8)

**Comment by andreamah** [comment]
Live Preview now works in Codespaces somewhat, but has difficulty showing the embedded preview without accessing the external preview first (redirects occur that cannot be framed in the iframe).

**Comment by akosyakov** [comment]
Tried in Gitpod, got the same issues.

**Comment by andreamah** [comment]
Will track codespaces issues in #111
