### ISSUE TITLE
Live preview extension startup error in vscode

### ISSUE THREAD

**Issue by ZZCabin** [microsoft/vscode-livepreview#584]
Hello, I would like to ask about the following error message of Live preview
 extension in vscode. Where are the generated logs stored?
![image](https://github.com/microsoft/vscode-livepreview/assets/113196043/96655962-fcad-44e5-979e-89bf2c6dcb5e)

**Comment by andreamah** [comment]
Try using the `Developer: Toggle Developer Tools` command to view the console. Does this happen for any other extensions?
