### ISSUE TITLE
subgrid css is incorrectly displayed

### ISSUE THREAD

**Issue by KorneyChervonenko** [microsoft/vscode-livepreview#586]
try this in browser and in livepreview:

    <style>
      .grid {
          background-color: cadetblue;
          display: grid;
          grid-template-columns: repeat(9, 1fr);
          grid-template-rows: repeat(5, minmax(100px, auto));
      }

      .item {
          background-color: gold;
          display: grid;
          grid-column: 3 / 8;
          grid-row: 2 / 5;
          grid-template-columns: subgrid;
          grid-template-rows: subgrid;
          /* grid-template-rows: repeat(3, 80px); */
      }

      .subitem {
          background-color: greenyellow;
          grid-column: 2 / 5;
          grid-row: 1 / 4;
      }

    </style>
  </head>

  <body>

    <div class="grid">
      <div class="item">
        <div class="subitem"></div>
      </div>
    </div>

  </body>
</html>

**Comment by andreamah** [comment]
I'm seeing the same thing in browser (opening the HTML file from the file explorer) and live preview. I'm using:

```
<!DOCTYPE html>
<html lang="en">
<style>
	.grid {
		background-color: cadetblue;
		display: grid;
		grid-template-columns: repeat(9, 1fr);
		grid-template-rows: repeat(5, minmax(100px, auto));
	}

	.item {
		background-color: gold;
		display: grid;
		grid-column: 3 / 8;
		grid-row: 2 / 5;
		grid-template-columns: subgrid;
		grid-template-rows: subgrid;
		/* grid-template-rows: repeat(3, 80px); */
	}

	.subitem {
		background-color: greenyellow;
		grid-column: 2 / 5;
		grid-row: 1 / 4;
	}
</style>

<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>

<body>
	<div class="grid">
		<div class="item">
			<div class="subitem"></div>
		</div>
	</div>
</body>

</html>
```

Can you show a screenshot of what you're seeing?

**Comment by KorneyChervonenko** [comment]
![live_preview](https://github.com/microsoft/vscode-livepreview/assets/139866589/d4d6fed5-2ddf-4d41-9af6-70065639ca1c)

**Comment by andreamah** [comment]
Which version of vscode and livepreview are you using?

**Comment by andreamah** [comment]
That's strange. I see the correct one:
<img width="1147" alt="image" src="https://github.com/microsoft/vscode-livepreview/assets/31675041/8bf1812c-df21-4285-bb41-0775f240fcf8">

If you use something like [`http-server`](https://www.npmjs.com/package/http-server) to host a server for your file, do you see the same thing? Or something different

**Comment by KorneyChervonenko** [comment]
updated VSC to 1.86. It works fine.
