### ISSUE TITLE
[Feature request] Follow `vscode://file/` links within the same editor window

### ISSUE THREAD

**Issue by lukstafi** [microsoft/vscode-livepreview#598]
Currently, my experience is that clicking on a `vscode://file/` link renders a blank page, and opening it in an external browser opens a fresh editor window / instance. My wish would be to open the file in the same editor window (in particular, the editor might be connected to a remote server e.g. on WSL). OK if this functionality is restricted to files from the same workspace as the previewed HTML page.

**Comment by andreamah** [comment]
I believe this behavior is in the core product instead of just with this extension. Please file it in the vscode repo's issue tracker. https://github.com/microsoft/vscode/issues
