### ISSUE TITLE
require manually refresh

### ISSUE THREAD

**Issue by xijn** [microsoft/vscode-livepreview#599]
First Thanks for your hard work and your tool is very useful.
i am not sure why , but in this last 2 days i have to manually click refresh to see changes , while before , it refresh by it self when i edit the code.
![image](https://github.com/microsoft/vscode-livepreview/assets/54191699/e47cda1a-3b6a-4ff1-a354-1e6888925766)

**Comment by andreamah** [comment]
Do you have any settings related to livepreview? Are you in a remote machine or in a codespace?

**Comment by xijn** [comment]
i think the problem is related to Autosave in VS code , you can mark this as solved , thanks
