### ISSUE TITLE
background: clip is not working in live preview

### ISSUE THREAD

**Issue by sujayun** [microsoft/vscode-livepreview#603]
The below Code adds Linear Gradient to the text in the Browser but not in the live preview

    `<body>
	<style>

		.box{
			width: 400px;
			height: 400px;
			background: linear-gradient(90deg,yellow,#00DD00);
			background-clip: text;
			color: transparent;
		}	
	</style>
    <h1 class="box">TxtYouWanDsp</h1>
</body>`

**Comment by gitspeaks** [comment]
The issue appears to be isolated to the use of background-clip: text; other values for background-clip operate as intended. This may stem from VS Code relying on an older version of the Edge browser. A temporary solution is to include the -webkit-background-clip: text; in your CSS.

**Comment by andreamah** [comment]
Yes, it could be that we are relying on an older version of electron to render this. Could you try following the suggestion above?
