### ISSUE TITLE
@scope rules not rendered 

### ISSUE THREAD

**Issue by gitspeaks** [microsoft/vscode-livepreview#606]
Works in Chrome/Edge.

https://caniuse.com/?search=%40scope

Example:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <style>
      @scope (.dark-scheme) {
        :scope {
          background-color: #333;
          color: #f0f0f0;
        }
      }
    </style>
  </head>
  <body>
    <div class="dark-scheme">
      <p>This is a paragraph in the dark scheme.</p>
    </div>
  </body>
</html>
```

**Comment by andreamah** [comment]
<img width="681" alt="image" src="https://github.com/microsoft/vscode-livepreview/assets/31675041/64ad6b4e-adb7-4447-af48-f30f5ff01e35">

This is what I see, which is what I would expect? Doesn't the scope apply to the paragraph?

**Comment by Snoopy1866** [comment]
@andreamah I think what he wanted to say was that a yellow underline may cause confsion. In my VSCode Editor, this yellow underline tells me a warning: `Unknown at rule @scope`，though it actually renders well in Chrome.

More details warning:

```json
[{
    "resource": "/C:/Users/wtwang/Documents/GitHub/learning-area/learn/style.css",
    "owner": "_generated_diagnostic_collection_name_#0",
    "code": "unknownAtRules",
    "severity": 4,
    "message": "Unknown at rule @scope",
    "source": "css",
    "startLineNumber": 1,
    "startColumn": 1,
    "endLineNumber": 1,
    "endColumn": 7
}]
```

![Image](https://github.com/user-attachments/assets/8d0e7f64-5f66-4bda-938e-086a33154640)
