### ISSUE TITLE
out put pb

### ISSUE THREAD

**Issue by jahnaviakshaya** [microsoft/vscode-livepreview#607]
Type: <b>Feature Request</b>

no matter what language i take i couldnt get the outputs and its always showing that there is something wrong with th extensions itself.....and its keep happening on moths at end .....and when my friends or any other uses this.....its working for them.....hell,its working for everyone except me which me making me loose interest

Extension version: 0.4.13
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by andreamah** [comment]
Can you show an example screenshot?
