### ISSUE TITLE
When I align developer tool on the right side, "Customize and Control DevTools" gets hidden

### ISSUE THREAD

**Issue by gitlearner246** [microsoft/vscode-livepreview#610]
And the only way to close DevTool is to close Vs Code, while when it's aligned at the bottom, you can close it anytime.
Even if I resize the DevTool window, it's fixed right on the top of the "Customize and Control DevTools" icon so nothing but closing VS Code can be done to close DevTool. I think it's a design flow for a software.
![Screenshot 2024-02-02 170426](https://github.com/microsoft/vscode-livepreview/assets/112508887/ed2a6f4b-0ae6-4c1d-9885-b4f5b4ef55b4)

**Comment by andreamah** [comment]
Can you file this in the main vscode repo? This also happens when you run `>Developer: Toggle Developer Tools` in the command palette. You could run that command again to close the devtools, but this is not ideal.

**Comment by gitlearner246** [comment]
It worked! Thank you so so much for your reply😊
