### ISSUE TITLE
hls video not playing

### ISSUE THREAD

**Issue by BAE86AEC1946B6AB60CCD7452DC811F0** [microsoft/vscode-livepreview#612]
```html
    <iframe
      src="https://nickdesaulniers.github.io/netfix/demo/bufferAll.html"
    ></iframe>

    <iframe src="https://hlsjs.video-dev.org/demo/"></iframe>

```

![image](https://github.com/microsoft/vscode-livepreview/assets/64393724/0d1da33d-e91b-47d7-9828-34ab7b9c4c45)

How can I play video?

**Comment by andreamah** [comment]
Does this also happen in the external preview?

**Comment by JosefJezek** [comment]
preview in browser is ok

**Comment by andreamah** [comment]
I think this might be a limitation of the webview itself. See here https://code.visualstudio.com/api/extension-guides/webview#supported-media-formats for the supported webview formats (and in turn, the ones supported in the Live Preview embedded browser)
