### ISSUE TITLE
Can't find the live preview icon

### ISSUE THREAD

**Issue by Okamoto-ripples** [microsoft/vscode-livepreview#617]
Can't find the live preview icon after installing it.
https://gyazo.com/15c4ff8761ce06758038086d18d50e18

**Comment by Okamoto-ripples** [comment]
No, can't see it still

**Comment by andreamah** [comment]
if you type `Live Preview` in the command palette, do you see anything?

**Comment by Okamoto-ripples** [comment]
nothing shows up
https://gyazo.com/24c557906301c2fa574005c73530aa54

**Comment by Okamoto-ripples** [comment]
@andreamah 
How is this going?

**Comment by andreamah** [comment]
That's strange. Do other extensions appear in the command palette? What happens if you reinstall the extension?

**Comment by Okamoto-ripples** [comment]
I don't have any other extensions. 
I've tried rebooting, reinstalling of the app and extension.
But nothing happens..

This issue is happening to my friend as well.

**Comment by andreamah** [comment]
Which VS Code version are you running?

**Comment by Okamoto-ripples** [comment]
![3a7a200cb4f5b3de528b00476293227d](https://github.com/microsoft/vscode-livepreview/assets/161555746/704590a2-200c-4e4b-97f9-1067a4eec12d)

1.87.0 I guess?

**Comment by andreamah** [comment]
> nothing shows up https://gyazo.com/24c557906301c2fa574005c73530aa54

Oh wait, I just noticed that you didn't have the `>` in this. Try typing `> Live Preview`.

**Comment by Okamoto-ripples** [comment]
These showed up 
https://gyazo.com/a78f9650f0f09993762f2ed23909aa0c

I tried ’Start server’ and this showed up
https://gyazo.com/724a10bb5726b51c027b6abcd891bddb

**Comment by andreamah** [comment]
You have two options:
1. open an html file in your editor- there should then be more options in the command palette and should be a 'preview button' like so: https://github.com/microsoft/vscode-livepreview?tab=readme-ov-file#html-file-previewing. I think this is what you're looking for.
2. Open up a folder in VS Code with your project, then live preview should run as if you started a server in that folder.

**Comment by Okamoto-ripples** [comment]
still not showing..
https://gyazo.com/9537f58fc5e9d00e4bdbaf27eca2b68a

**Comment by andreamah** [comment]
You need a file that ends in `.html`. That file is an `.ini` file.
