### ISSUE TITLE
Test VS Live Server/Preview - opening a file using a link from the terminal

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode-livepreview#62]
Testing microsoft/vscode#127164

When clicking on the link to a file in the terminal, I am wondering whether we should be opening this file in a separate editor group than the preview itself. This way, you can see both the file that you have chosen to open as well as the preview itself. We could also make this configurable to give users more flexibility on how the files are being opened.

**Comment by andreamah** [comment]
fixed upstream with https://github.com/microsoft/vscode/issues/131677
