### ISSUE TITLE
it is not working

### ISSUE THREAD

**Issue by aditya0090** [microsoft/vscode-livepreview#620]
Type: <b>Feature Request</b>

my live preview is not working 

Extension version: 0.4.13
VS Code version: Code 1.87.1 (1e790d77f81672c49be070e04474901747115651, 2024-03-06T00:21:36.258Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by andreamah** [comment]
can you show a screenshot of the behavior?
