### ISSUE TITLE
it is not working properly

### ISSUE THREAD

**Issue by aditya0090** [microsoft/vscode-livepreview#622]
Type: <b>Feature Request</b>

it is not working

Extension version: 0.4.13
VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:41:44.469Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by andreamah** [comment]
Can you provide a screenshot?
