### ISSUE TITLE
Live Preview Button not showing

### ISSUE THREAD

**Issue by rupam2232** [microsoft/vscode-livepreview#624]
Live Preview button is not showing in latest version at my vs code. When I first downloaded it, there was that button, but now it's not showing there.
![Screenshot 2024-03-17 205207](https://github.com/microsoft/vscode-livepreview/assets/163750580/8a1ec65f-e579-4c81-a961-8d373af0f1ba)

**Comment by andreamah** [comment]
That's strange. If you use `CTRL+SHIFT+P` to open the command palette and type "Live Preview", does anything show up?

**Comment by rupam2232** [comment]
yeah see
![Screenshot 2024-03-21 114101](https://github.com/microsoft/vscode-livepreview/assets/163750580/5a8da244-365f-4972-83f7-a9ded682e2bb)

**Comment by andreamah** [comment]
If you right click the area where the preview button should be, what do you see?

<img width="419" alt="image" src="https://github.com/microsoft/vscode-livepreview/assets/31675041/bd066ec4-42d6-431c-a3d2-ff8381793b17">

**Comment by rupam2232** [comment]
like this ?
![Screenshot 2024-03-22 152018](https://github.com/microsoft/vscode-livepreview/assets/163750580/2ec0c4f1-001e-434e-9b2b-b2839786f73b)

**Comment by andreamah** [comment]
No, right-click on the yellow icon in your screenshot.

**Comment by rupam2232** [comment]
now see
![Screenshot 2024-03-23 105714](https://github.com/microsoft/vscode-livepreview/assets/163750580/6efee7e0-bfe2-40f6-85d1-01f729e89dcc)

**Comment by andreamah** [comment]
Can you click "show preview" such that it's checked off?

**Comment by rupam2232** [comment]
oh yeah the button is now visible thank you very much
