### ISSUE TITLE
live preview not showing up while using Github Repositories extension

### ISSUE THREAD

**Issue by lucas09jps** [microsoft/vscode-livepreview#626]
I want to use the Github Repositories extension so I can edit my code and repository using VScode without needing to clone a git. However, when trying to use Microsoft Live-Preview with it, there was no option to initiate live-preview. I also tried initiating it using the command pallet but was unsuccessful. However, when closing the window and opening a local file it worked.
<img width="957" alt="Captura de Tela 2024-03-24 às 21 21 05" src="https://github.com/microsoft/vscode-livepreview/assets/103185523/cb1c8d58-6b9d-4ad4-8d84-2fc3961dc162">
<img width="967" alt="Captura de Tela 2024-03-24 às 21 21 27" src="https://github.com/microsoft/vscode-livepreview/assets/103185523/f2bbad63-630b-4715-b241-86dd24a0dc06">
<img width="268" alt="Captura de Tela 2024-03-24 às 21 21 49" src="https://github.com/microsoft/vscode-livepreview/assets/103185523/3abe21bb-c683-4dff-87c3-9635deb4160d">

**Comment by andreamah** [comment]
There currently is no support for this. I will track progress on https://github.com/microsoft/vscode-livepreview/issues/489
