### ISSUE TITLE
just white，cannot work normal

### ISSUE THREAD

**Issue by chall1123** [microsoft/vscode-livepreview#627]
![image](https://github.com/microsoft/vscode-livepreview/assets/37236882/9905a1fb-5aee-4e24-881b-983efa175e07)
version 2024010901
vscode version 1.81.1

**Comment by andreamah** [comment]
Can you open the developer tools? In the command palette, run `Developer: Toggle Developer Tools`.

**Comment by likui1123** [comment]
> Can you open the developer tools? In the command palette, run `Developer: Toggle Developer Tools`.
@andreamah i can open developer tools, i used remote ssh extension,vscode work in linux
![image](https://github.com/microsoft/vscode-livepreview/assets/37236882/54871480-3c17-4838-8b97-369a5e83c55d)

**Comment by sultanmyrza** [comment]
Same thing here 

In the beginning live preview was working ok. However after finishing mdn [PWA tutorial](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps) I started doing 2nd mdn [PWA tutorial ](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Tutorials/js13kGames). I started by creating new directory and new index.hml
<details>
<summary>Here is the contents of index.html</summary>

```hml
<!DOCTYPE html>
<html lang="en">
  <head>
    <head>
      <meta charset="utf-8" />
      <title>js13kGames A-Frame entries</title>
      <meta
        name="description"
        content="A list of A-Frame entries submitted to the js13kGames 2017 competition, used as an example for the MDN articles about Progressive Web Apps."
      />
      <meta name="author" content="end3r" />
      <meta name="theme-color" content="#B12A34" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta
        property="og:image"
        content="https://js13kgames.com/img/js13kgames-banner.png"
      />
      <link rel="icon" href="favicon.ico" />
      <link rel="stylesheet" href="style.css" />
      <link rel="manifest" href="js13kpwa.webmanifest" />
      <script src="data/games.js" defer></script>
      <script src="app.js" defer></script>
    </head>
  </head>
  <body>
    <header>
      <p>
        <a href="https://js13kgames.com" class="logo">
          <img src="img/js13kgames.png" alt="js13kGames" />
        </a>
      </p>
    </header>
    <main>
      <h1>js13kGames A-Frame entries</h1>
      <p class="description">
        <a href="https://js13kgames.com/aframe">A-Frame category</a> in the
        <a href="https://2017.js13kgames.com">js13kGames 2017</a> competition.
        You can
        <a href="https://github.com/mdn/pwa-examples/blob/main/js13kpwa"
          >fork js13kPWA on GitHub</a
        >
        to check its source code.
      </p>
      <button id="notifications">Request dummy notifications</button>
      <section id="content">TODO: Content inserted in here</section>
    </main>
    <footer>
      <p>
        © js13kGames 2012-2018, created and maintained by
        <a href="https://end3r.com">Andrzej Mazur</a> from
        <a href="https://enclavegames.com">Enclave Games</a>.
      </p>
    </footer>
  </body>
</html>
```
</details>

However when I start live preview I see white screen. I open dev tools and here is the screenshot
<img width="1512" alt="Screenshot 2024-03-30 at 5 08 08 PM" src="https://github.com/microsoft/vscode-livepreview/assets/12681781/7da95711-6412-4c96-a248-36dc77650e69">

I know Live Preview is in "preview mode" but team already did a great job. And I really enjoy using it but can't use it now.

**Comment by sultanmyrza** [comment]
In my previous [resonse](https://github.com/microsoft/vscode-livepreview/issues/627#issuecomment-2027996910) it's using port :3000. And I change Live Preview to use port :3001 and it works as expected.

<img width="1512" alt="Screenshot 2024-03-30 at 7 33 25 PM" src="https://github.com/microsoft/vscode-livepreview/assets/12681781/5d93d967-cebe-47cd-aaf7-2f013493d06f">

I can use Live Preview now however it's not best workaround since I will keep changin ports. Is there a way to clear Live Preview cache or something?

**Comment by chall1123** [comment]
> In my previous [resonse](https://github.com/microsoft/vscode-livepreview/issues/627#issuecomment-2027996910) it's using port :3000. And I change Live Preview to use port :3001 and it works as expected.
> 
> <img alt="Screenshot 2024-03-30 at 7 33 25 PM" width="1512" src="https://private-user-images.githubusercontent.com/12681781/318190460-5d93d967-cebe-47cd-aaf7-2f013493d06f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NTE5MTUsIm5iZiI6MTcxMTg1MTYxNSwicGF0aCI6Ii8xMjY4MTc4MS8zMTgxOTA0NjAtNWQ5M2Q5NjctY2ViZS00N2NkLWFhZjctMmYwMTM0OTNkMDZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDAyMjAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMTIyZmUyMjFlODA3NjgyZjlhNGJjZjVhN2JiYzM5YmJjMjA0OGZkMjMxMTg4NDU4NjRmNmQ2YTUxMWU4NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M9RFQpsaOQLtRGrewxE7VGk6flba2OUojfHB_7Y66KQ">
> I can use Live Preview now however it's not best workaround since I will keep changin ports. Is there a way to clear Live Preview cache or something?

very good, I change Live Preview port number, my Live Preview  extension can work normal,I hope your problem can also be solved

**Comment by sultanmyrza** [comment]
@chall1123, glad it worked for you but I still feel it's not good workaround and feels like I'm "polluting" ports. Rather it would be nice if there were better "right" solution.

**Comment by andreamah** [comment]
Perhaps this is a good use case of https://github.com/microsoft/vscode-livepreview/issues/333, where there would be auto-finding of an IP address to prevent collisions.

**Comment by andreamah** [comment]
Alternatively, you can select a different IP address in `livePreview.hostIP` if you can't anticipate a free port on `127.0.0.1`. Although livePreview should have its own logic to try not to occupy a port that is already being hosted on.
