### ISSUE TITLE
An unknown error occurred. Please consult the log for more details. 

### ISSUE THREAD

**Issue by dcdb723** [microsoft/vscode-livepreview#635]
when I open vscode trying to preview my html file. it shows the error: An unknown error occurred. Please consult the log for more details. 

From the log of the extension host log, it says: [error] undefined livePreview.start.preview.atFile {"value":"ms-vscode.live-server","_lower":"ms-vscode.live-server"}
anyone know what's going on here?

**Comment by andreamah** [comment]
Are you on a remote of some sort? Remote tunnels or codespaces?

**Comment by dcdb723** [comment]
> Are you on a remote of some sort? Remote tunnels or codespaces?
> 
> What do you see in the console when you run `Developer: Toggle Developer Tools`?

nah i wasn't on remote. This problem happened on my Windows PC, I tried the same project on the same day on my Mac it worked fine, after a day it worked again on my Windows PC, I didn't change anything. I don't really know whats going on

**Comment by vanowm** [comment]
For these who might have same issue, the solution that worked for me was to restart `winnat` by runing these commands:
```
net stop winnat
net start winnat
```
