### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ZamoraAfra** [microsoft/vscode-livepreview#636]
i have it downloaded but the preview button isn't there

**Comment by sumitkumar4095** [comment]
i have it downloaded but the preview button isn't there

**Comment by andreamah** [comment]
Are you on an html file?

**Comment by exmateriae** [comment]
@andreamah I installed it a few minutes ago and I have the same issue. I'm on html files, I tried several different ones

**Comment by andreamah** [comment]
If you open the command palette, can you search for live preview commands?

**Comment by exmateriae** [comment]
It works through the command palette thank you! I don't think often enough about trying the palette, I'll remember that

**Comment by giohappy** [comment]
Same for me. No Live Preview context menu, or live preview icon.
The command palette shows the option to start the Live Preview server

**Comment by andreamah** [comment]
Are you on a remote or a codespace?

**Comment by giohappy** [comment]
It's a local environment.

**Comment by andreamah** [comment]
Strange. If auto-updating is not working, this means that the websocket server isn't starting. What do you see in the console when you run `Developer: Toggle Developer Tools`?

**Comment by andreamah** [comment]
Does this get fixed when you try an earlier version?
