### ISSUE TITLE
Add a "Start Preview" button

### ISSUE THREAD

**Issue by Firestar-Reimu** [microsoft/vscode-livepreview#638]
Add a **"Start Preview" button** so that we do not need to press `ctrl+shift+P` and find the `start preview` for ages. 

![屏幕截图_20240512_172614](https://github.com/microsoft/vscode-livepreview/assets/65082432/b104f47c-aa14-4fd0-a6a2-7c4f1663219b)

Like this:

![图片](https://github.com/microsoft/vscode-livepreview/assets/65082432/796c98bd-360e-4301-bf86-a1970dff5f3b)

**Comment by tullyd43** [comment]
You can right click inside the HTML file and click "Show Preview". This will let you view the file within VSCode and make changes displayed live. It will automatically start the server. Or assign a custom keyboard shortcut

**Comment by andreamah** [comment]
> You can right click inside the HTML file and click "Show Preview". This will let you view the file within VSCode and make changes displayed live. It will automatically start the server. Or assign a custom keyboard shortcut

This is the correct answer. Thanks!
