### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by kmr-ankitt** [microsoft/vscode-livepreview#641]
# Live Preview not working, tried reinstalling both vs code and extension but did'nt worked.

Whenever it click show preview it shows this: 

![image](https://github.com/microsoft/vscode-livepreview/assets/90329779/d753fff8-5a19-4fb5-8255-d621483464ff)

**Comment by andreamah** [comment]
Are you on a local installation of vscode, or in a web browser (ie: codespace)? What version of vscode are you running? Are there any errors listed in the the `Window` or `Extension Host` logs in the `Output` tab?

**Comment by kmr-ankitt** [comment]
> Are you on a local installation of vscode, or in a web browser (ie: codespace)? What version of vscode are you running? Are there any errors listed in the the `Window` or `Extension Host` logs in the `Output` tab?

i got it fixed, it actually asked for latest version of golang
