### ISSUE TITLE
FR: It would be nice to sync the preview with the code

### ISSUE THREAD

**Issue by sonique6784** [microsoft/vscode-livepreview#642]
Feature Request

It would be nice to sync the preview with the code:
- if user scroll in the preview, the code scroll to the same place
- if user click in the preview on the code editor scroll to the right place and highlight the line.

These features are available in "HTML Preview" by "George Oliveira".

**Comment by andreamah** [comment]
duplicate of https://github.com/microsoft/vscode-livepreview/issues/214
