### ISSUE TITLE
Option blocked when DevTools docked to right side

### ISSUE THREAD

**Issue by tullyd43** [microsoft/vscode-livepreview#647]
Type: <b>Bug</b>

When docking the DevTools Pane to the right side of the editor, the controls at the top right are blocked by the "X (exit app)", "__"(minimize), and "full screen" buttons. The only way I can get it to go away is to close VsCode and re open it so the DevTools pane closes.

Extension version: 0.4.13
VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (14.69GB free)|
|Process Argv|--crash-reporter-id ba31e7a8-3a2b-4055-b820-d53a215f6800|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by andreamah** [comment]
This is an upstream issue in vscode, see https://github.com/microsoft/vscode/issues/168454#issuecomment-1737938292
