### ISSUE TITLE
Extensão não funciona.

### ISSUE THREAD

**Issue by Jessika-Andrade** [microsoft/vscode-livepreview#651]
Semana passada, a extensão sumiu. Acreditei ser por conta das quedas da internet. Uns dias depois, voltou.
E então caiu novamente. Já reiniciei, fechei, desinstalei... Mesmo assim, a extensão não volta a funcionar.
O que posso fazer para conseguir acesso?
![image](https://github.com/microsoft/vscode-livepreview/assets/173556217/20b7579e-8333-41a4-ac3f-c308544cfaab)

**Comment by andreamah** [comment]
Are you on an html file when you look for the icon?
