### ISSUE TITLE
 O Windows não pode encontrar "default".

### ISSUE THREAD

**Issue by SrJotaG** [microsoft/vscode-livepreview#652]
Estava fazendo um site de foruns no firebase, decidi ver como estava. e me deparei com esse erro: 
![image](https://github.com/microsoft/vscode-livepreview/assets/158376175/ea9c15b2-af02-41e4-a6d2-3a186f6b6b2f)

Se alguém sabe o motivo do erro, me ajuda.

**Comment by andreamah** [comment]
Would you be able to use English? Just so I can help you better :)
