### ISSUE TITLE
Auto-refresh triggered when file outside of server root is edited

### ISSUE THREAD

**Issue by louwers** [microsoft/vscode-livepreview#653]
In a multi-root workspace

```
- src1
  - index.html
- src2
  - some-other-file.txt
```

When 
```
    "livePreview.serverRoot": "src1"
```

is set, the auto-refresh is triggered even though `some-other-file.txt` is edited.

I don't know if this is intentional behavior. If it is, it would be good to have a configuration option available to ignore file paths for the live reload.

**Comment by lamrongol** [comment]
#691 is my hypotheses but cause may be that an external app changes files in `.git` folder.
