### ISSUE TITLE
An unknown error occurred. Please consult the log for more details. [FIX]

### ISSUE THREAD

**Issue by arin-s** [microsoft/vscode-livepreview#656]
Duplicate of #635 #601 and possibly #499
In exthost.log I see:
`[error] undefined livePreview.start.preview.atFile {"value":"ms-vscode.live-server","_lower":"ms-vscode.live-server"}`
In the developer console:
`Unknown error: Error: listen EACCES: permission denied 127.0.0.1:3000`
![Code_uZEGtmpGog](https://github.com/microsoft/vscode-livepreview/assets/147359526/9afdf375-4de0-40aa-a66a-b435c98c730f)
Unlike what others have mentioned, installing an older version does NOT help.
Restarting the Host Network Service as mentioned [here](https://stackoverflow.com/questions/67292618/eacces-permission-denied-0-0-0-03000-in-windows-next-js) then reopening vscode solves the issue.
I have no idea how to replicate the error though, it occurs randomly.
Hope this helps.

**Comment by andreamah** [comment]
I think that something else is using 127.0.0.1 on your machine. If you set `livePreview.hostIP` to a different valid local IP address, does the same happen?

**Comment by arin-s** [comment]
Hi, sorry I forgot to reply to this.
I found the source of the problem.
Hyper-V has a habit of reserving hundreds of random ports at a time.
The annoying thing is that this won't even show up using netstat or other standard port monitoring methods.
The main fix:
in command prompt: `netsh int ipv4 set dynamic tcp start=60001 num=5534` then reboot

This is all detailed in the stackoverflow post below:
https://stackoverflow.com/questions/63257991/port-not-shown-to-be-used-in-netstat-but-trying-to-use-the-port-is-denied-by-wi

Cheers.
