### ISSUE TITLE
Shortcut keys for Live Preview.

### ISSUE THREAD

**Issue by pranshu7800** [microsoft/vscode-livepreview#66]
Do we have any shortcut keys for live preview?

**Comment by andreamah** [comment]
There aren't any defaults, but you can set them yourself in using the `Preferences: Open Keyboard Shortcuts` command in the command palette.
![image](https://user-images.githubusercontent.com/31675041/125303018-b7922e00-e2e9-11eb-9a96-59f3a7886771.png)

Then, you can search for `LivePreview` and then set a keybinding for whichever command you want (note that commands that do not specify a preview target as external/internal will just use your default option)

![image](https://user-images.githubusercontent.com/31675041/125303362-fa540600-e2e9-11eb-8bf0-abf80f4408aa.png)

**Comment by pranshu7800** [comment]
Is there any future possibility to create the default one?

**Comment by andreamah** [comment]
We likely aren't going to introduce default ones, since users can just configure them if they want them. It may be annoying for users who don't use that keybinding to have an extra keybinding used up.
