### ISSUE TITLE
Icon got disappear

### ISSUE THREAD

**Issue by disha9213-dp** [microsoft/vscode-livepreview#662]
Subject: Missing Live Preview Extension Icon

Hi there,

I'm writing to report an issue with the Live Preview extension. While the extension itself seems to be working, the icon is missing from my toolbar.

This makes it difficult to quickly access the Live Preview features. It would be great if you could look into this and hopefully provide a fix soon.

Thanks,
```[tasklist]
### Tasks
```

**Comment by andreamah** [comment]
Can you give a screenshot? Are you currently on an html file?
