### ISSUE TITLE
Missing icon of extension

### ISSUE THREAD

**Issue by disha9213-dp** [microsoft/vscode-livepreview#663]
Subject: Missing Live Preview Extension Icon

Hi there,

I'm writing to report an issue with the Live Preview extension. While the extension itself seems to be working, the icon is missing from my toolbar.

This makes it difficult to quickly access the Live Preview features. It would be great if you could look into this and hopefully provide a fix soon.

Thanks,
![Uploading WhatsApp Image 2024-07-13 at 13.24.00_f01503dd.jpg…]()

```[tasklist]
### Tasks
```

**Comment by akirataguchi115** [comment]
Could you upload the image again? It doesn't seem to have uploaded correctly.

**Comment by disha9213-dp** [comment]
![WhatsApp Image 2024-07-20 at 13 09 26_6b4524c8](https://github.com/user-attachments/assets/31be615c-edc8-4ce9-b2fb-71ca75c8e1be)

**Comment by disha9213-dp** [comment]
SEE ON THE UPPER RIGHT CORNER

**Comment by andreamah** [comment]
See https://github.com/microsoft/vscode-livepreview/issues/680
