### ISSUE TITLE
The IP address "192.168.0.102" cannot be used to host the server. Using default IP 127.0.0.1.

### ISSUE THREAD

**Issue by srikanthsoft2001** [microsoft/vscode-livepreview#668]
The IP address "192.168.0.102" cannot be used to host the server. Using default IP 127.0.0.1.

**Comment by andreamah** [comment]
/duplicate https://github.com/microsoft/vscode-livepreview/issues/588

**Comment by TanviKamath** [comment]
facing the same issue

**Comment by MEETJAIN136** [comment]
facing the same issue
