### ISSUE TITLE
it would be nice to add inspect element

### ISSUE THREAD

**Issue by marksamfd** [microsoft/vscode-livepreview#67]
by hovering in elements in editor

**Comment by andreamah** [comment]
duplicate of #149

**Comment by candideu** [comment]
If you're still looking for an alternative VS Code extension: [Five Server](https://github.com/yandeu/five-server-vscode) is able to jump to a section of a preview when you double-click or edit a section of your code. It can also highlight the code you are working on in your browser, update your files instantly while typing on your keyboard, and navigate your live preview automatically to the current editing file.

![image](https://raw.githubusercontent.com/yandeu/five-server/main/img/vscode-preview.gif)

Only downside is that there's no Workspace Multi-root support yet.
