### ISSUE TITLE
Support using local server..

### ISSUE THREAD

**Issue by erikdemarco** [microsoft/vscode-livepreview#678]
its a repoened of this #187. because the current suggustion is to use simple browser, which is not comparable. as simple browser doesnt integrate the debugger or console.log() output. also ms edge tools use too much system resources. live preview is in the sweet spot for most developers.

**Comment by andreamah** [comment]
you can still do those things in the simple browser:
- For debugging, run `Debug: Open Link` in the command palette, then the link to your server. This is pretty much what Live Preview does, but with its custom server.
- For console.logs, it should show in the debug panel when you debug, but you can also run `Developer: Toggle Developer Tools` to show the console logs.
