### ISSUE TITLE
Icon not appearing

### ISSUE THREAD

**Issue by Tintouin** [microsoft/vscode-livepreview#679]
This is a slighly different issue than the other like this here. 

<img width="1491" alt="Capture d’écran 2024-08-28 à 13 54 05" src="https://github.com/user-attachments/assets/130bfd63-ea6c-475c-8e19-f9e0c8a69401">

Basically I'm on a .html file, an the icon does not show up. 

It works when I enter the command `>Live preview: Start server` but that is the only way I can get it to work...

Anyway that may be because I use VSCodium, but I dont understand why it would do that... Its the same code so... Maybe you have an idea why.

**Comment by andreamah** [comment]
have you tried https://github.com/microsoft/vscode-livepreview/issues/680?

**Comment by Tintouin** [comment]
Yes !
But I only have these options :
<img width="313" alt="Capture d’écran 2024-09-03 à 20 24 26" src="https://github.com/user-attachments/assets/456ce02f-13a4-4850-8506-0a9a98fd1c8b">
and also these on the three dots :

<img width="266" alt="Capture d’écran 2024-09-03 à 20 24 55" src="https://github.com/user-attachments/assets/18e743dc-76b1-4e0b-913d-67db7cea1282">

**Comment by andreamah** [comment]
Oh, you're on VS Codium. I have no idea, since I don't work on that. I'm assuming that there's a bug in how they support extension-contributed icons, but unfortunately, I only make sure that it works in VS Code.

**Comment by Tintouin** [comment]
Tested again and it's in fact because of VScodium, I'll dig a bit more so you can fix it later on if possible.

**Comment by faizanMehtab** [comment]
![Capture](https://github.com/user-attachments/assets/69068380-e37f-439b-931c-7bf5ac000fbb)
right click on the blue circled box and than click show show preview

**Comment by faizanMehtab** [comment]
![Capture](https://github.com/user-attachments/assets/daa056e7-29f9-4987-afd9-b6e39d821984)
right click on the blue circled box and than click show preview
