### ISSUE TITLE
High CPU usage with External Browser

### ISSUE THREAD

**Issue by ZorinArch** [microsoft/vscode-livepreview#68]
Hi,

When i open html file in external browser it consume a lot of CPU resources, this only happens with any external browser.

Thanks,

**Comment by jasonwilliams** [comment]
I've noticed this too. I've traced it down to this:
https://github.com/microsoft/vscode-livepreview/blob/569ad2502b2064163a0caedce396c13dfda9087a/media/inject_script.html#L24-L31

it runs a lot, not sure if its some infinite loop.
![highLoad](https://user-images.githubusercontent.com/936006/125352846-b13b9a80-e359-11eb-80e2-c7cfcb25c9c3.gif)

**Comment by andreamah** [comment]
Amazing catch @jasonwilliams! I'll merge a PR soon to fix this.
