### ISSUE TITLE
Icon Not appear

### ISSUE THREAD

**Issue by Binteimran853** [microsoft/vscode-livepreview#680]
When I install live Preview extension then it's icon is not showing, even I restart my VS code editor

**Comment by kri-kan** [comment]
yes, same here. I even have a opened html file and still the live preview icon doesn't appear. Rather the option went like a menu button into the right side ellipsis.
![image](https://github.com/user-attachments/assets/d44f4c8f-04c3-4d73-8a00-5267b2b6adc6)

**Comment by andreamah** [comment]
If you right-click on the button for splitting the editor, do you have "Show Preview" checked off?


![Image](https://github.com/user-attachments/assets/725556fd-e7fa-448f-911c-92f09cc9803b)

**Comment by kri-kan** [comment]
Oh, that worked! But right click menu on an icon to manage other icons was not very intuitive though.

**Comment by andreamah** [comment]
> Oh, that worked! But right click menu on an icon to manage other icons was not very intuitive though.

This is a built-in feature in VS code. If you want the hide/show icons to be different, please file an issue with vscode itself.
