### ISSUE TITLE
Refresh delay option

### ISSUE THREAD

**Issue by gearskullguy** [microsoft/vscode-livepreview#685]
Hi, love the extension. I found the auto-update to be far too fast for my liking. I found the option to toggle it for auto-save or not, but that's too extreme. I'm requesting that the option for a delay instead (with a default refresh rate of say 1000ms, that's editable), like how VS Code has a setting for auto-save delay. Thank you!

**Comment by andreamah** [comment]
Try setting `search.searchOnTypeDebouncePeriod` to a larger number. That will delay the auto-refresh.
