### ISSUE TITLE
Add option to choose default external browser

### ISSUE THREAD

**Issue by ZorinArch** [microsoft/vscode-livepreview#69]
Hi,

Please, add option to choose default external browser.

Thanks,

**Comment by chevnix** [comment]
Yes! This is simple yet useful feature.

**Comment by andreamah** [comment]
Live Preview already has an option to have the preview open to the external browser by default:
![image](https://user-images.githubusercontent.com/31675041/125301184-f1facb80-e2e7-11eb-98d7-c4fe3a1cd786.png)

However, it doesn't have an option to choose the browser executable to run yet, which is what I'm assuming that you all are referring to?

**Comment by chevnix** [comment]
@andreamah That's what I mean. With that option it can open whatever browser we assign not just default one.

**Comment by Pawper** [comment]
Is changing our system's default browser the only way? I currently use Chrome as my default browser, but I want to use the Live Preview extension with the Edge Tools extension.

**Comment by fishmi** [comment]
This option would be helpful for me as well, since like Pawper I prefer Edge as a browser for development, but not as a default browser.

**Comment by takinabradley** [comment]
Been looking for a solution to this, and just found this issue. I would definitely appreciate this feature, as I prefer different browsers for development and general use.

**Comment by TD540** [comment]
Has anybody here found a solution to this yet?

**Comment by TD540** [comment]
Is there really nobody who would find it more useful if you could configure Live Previews to open by default in a different browser?
