### ISSUE TITLE
SVGs are served with incorrect Content-Type

### ISSUE THREAD

**Issue by niklas-e** [microsoft/vscode-livepreview#690]
## Problem

Using SVG files as `<img/>` `src` is not working in live preview. Images are shown as broken/not found.

![image](https://github.com/user-attachments/assets/f238f661-32c1-4d4f-8fae-629cb977507a)

## Probable cause

Looks like SVGs are served as `text/html` instead of `image/svg+xml`

Current response headers for a SVG:

![image](https://github.com/user-attachments/assets/b4dba526-d169-43e8-8348-42a97e6c604c)

**Comment by andreamah** [comment]
Are you using the latest version of Live Preview? They have the correct content type for me.

![Image](https://github.com/user-attachments/assets/e5e762dc-3888-4edf-948a-5e077d447fff)

![Image](https://github.com/user-attachments/assets/2007da60-9826-415c-9d1e-033f8386a784)

**Comment by niklas-e** [comment]
Hmm, weird, now it seems to work correctly 🤔 

I have `v0.4.15` installed.

Since this seems to not be an issue, I'll close this one, sorry for the hassle.
