### ISSUE TITLE
[Feature request] Ignore `.git` folder as default not to auto-refresh arbitrarily

### ISSUE THREAD

**Issue by lamrongol** [microsoft/vscode-livepreview#691]
This is already mentioned at https://github.com/microsoft/vscode-livepreview/issues/276#issuecomment-1711470094 and https://github.com/microsoft/vscode-livepreview/issues/548 exists but I think `.git` folder is especially important and create a new issue.
If Auto Refresh Preview settings ( vscode://settings/livePreview.autoRefreshPreview ) is "On Changes to Saved Files", auto-refresh is triggered even when files in `.git` folder are changed. 
Files in `.git` folder doesn't affect Web page itself and they would be changed by external apps.
In my case, app named "Sourcetree" fetch automatically and `FETCH_HEAD` is reloaded periodically and auto refresh is triggered arbitrarily.

I think other apps may cause such a problem so ignoring ".git" folder for  "On Changes to Saved Files" is needed.
https://github.com/microsoft/vscode-livepreview/issues/653 may be same cause.

`Ignore` settings( https://github.com/microsoft/vscode-livepreview/issues/548 ) may be also required but adding `.git` as default is needed and doesn't cause a problem, I think.

**Comment by andreamah** [comment]
Please see https://github.com/microsoft/vscode-livepreview/issues/653#issuecomment-2374471722
