### ISSUE TITLE
Allow intra-workspace links to open files

### ISSUE THREAD

**Issue by joshburkart** [microsoft/vscode-livepreview#693]
Hello,

I work at a company where we have an internal code visualization application as a static HTML file. This is located inside a code repo that engineers check out to their workstations. It's most convenient for us to view this page within VSCode using this extension, which works really well. However, it would be even more useful if it was possible to have links in the static HTML file that, when clicked, would open a file within the repository, while still staying within VSCode. Is this possible somehow...?

Thanks!

**Comment by andreamah** [comment]
If you enable server logging (`Start Server Logging`), then it will give you links that you can click on whenever it serves a file. It should follow whatever configuration you have for clicking on links in the terminal, so `alt+click` or `ctrl+click` to open a link.

https://github.com/microsoft/vscode-livepreview?tab=readme-ov-file#persistent-server-task-with-server-logging

**Comment by joshburkart** [comment]
Ah, that's useful, thank you! It seems to only open up the file in the same browser tab, though -- I was hoping it'd be possible to open up a file using a normal VSCode editor tab. I think I need to investigate the `vscode://` URL handler, which seems out of scope for an issue filed against this extension. Closing.

**Comment by andreamah** [comment]
oh, does it not open the editor? 
![Image](https://github.com/user-attachments/assets/0c1d6e6f-e87b-4fcd-85b0-347efdc28049)

When I ctrl+click on this, it opens the file in the editor. Is it not the same for you?
