### ISSUE TITLE
Support local area network ip 

### ISSUE THREAD

**Issue by LancelotLewis** [microsoft/vscode-livepreview#97]

**Comment by LancelotLewis** [comment]
There is a simple test page
It works well in 127.0.0.1
![image](https://user-images.githubusercontent.com/8749615/126580616-5c9bc362-e43b-44d1-92ff-b5e01cd45e6b.png)

But it's not working at 192.168.1.234
![image](https://user-images.githubusercontent.com/8749615/126580656-c5baf5a0-d48b-46ca-8f80-a928d41fbbf3.png)

**Comment by andreamah** [comment]
This is done intentionally to just host on `127.0.0.1`. What is the reason why you need all local addresses to be supported?

**Comment by LancelotLewis** [comment]
Some time i need preview this project in my phone, but `127.0.0.1` can't satisfy this feature
So i think another local address might help this situation

**Comment by andreamah** [comment]
Would it be enough to add a setting to the extension to specify the IP to host on if not `127.0.0.1`?

**Comment by LancelotLewis** [comment]
> Would it be enough to add a setting to the extension to specify the IP to host on if not `127.0.0.1`?

I think it's good 👍

**Comment by rchiodo** [comment]
@andreamah do you have any verification steps you could add?

**Comment by andreamah** [comment]
@rchiodo Yup! Try setting `livePreview.hostIP: <an ip adddress>` and the next time you start the server, it should use that address. See this PR for reference: https://github.com/microsoft/vscode-livepreview/pull/117
