### ISSUE TITLE
Remember already opened preview in embedded browser

### ISSUE THREAD

**Issue by pgfearo** [microsoft/vscode-livepreview#99]
Similar to #92 but for the embedded browser:

Current behaviour is that any pre-existing editor group html preview tab is replaced by the new preview tab. 

It would be useful to have more than one preview tab open at a time so I can see the results of running VSCode tasks that modify more than one file at a time.

**Comment by andreamah** [comment]
We currently don't have plans to support multiple embedded windows, see rationale in #84.
